# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_stream_processor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasStreamProcessor
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_stream_processor,
      attributes_class: Mongodbatlas::Types::StreamProcessorAttributes,
      outputs: { id: :id },
      map: [:instance_name, :pipeline, :processor_name, :project_id],
      map_present: [:options]
  end
  module Mongodbatlas
    include MongodbatlasStreamProcessor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
