# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class StreamProcessorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :instance_name, T::String
    attribute :pipeline, T::String
    attribute :processor_name, T::String
    attribute :project_id, T::String
    attribute? :options, T::Hash.optional
  end
end
