# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_global_cluster_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasGlobalClusterConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_global_cluster_config,
      attributes_class: Mongodbatlas::Types::GlobalClusterConfigAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :project_id],
      map_present: [:custom_zone_mappings, :managed_namespaces]
  end
  module Mongodbatlas
    include MongodbatlasGlobalClusterConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
