# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class GlobalClusterConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :cluster_name, T::String
    attribute :project_id, T::String
    attribute? :custom_zone_mappings, T::Array.of(T::Hash).optional
    attribute? :managed_namespaces, T::Array.of(T::Hash).optional
  end
end
