# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_project_ip_access_list/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasProjectIpAccessList
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_project_ip_access_list,
      attributes_class: Mongodbatlas::Types::ProjectIpAccessListAttributes,
      outputs: { id: :id },
      map: [:project_id],
      map_present: [:timeouts]
  end
  module Mongodbatlas
    include MongodbatlasProjectIpAccessList
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
