# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class PrivatelinkEndpointAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :project_id, T::String
    attribute :provider_name, T::String
    attribute :region, T::String
  end
end
