# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_privatelink_endpoint_service_data_federation_online_archive/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasPrivatelinkEndpointServiceDataFederationOnlineArchive
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_privatelink_endpoint_service_data_federation_online_archive,
      attributes_class: Mongodbatlas::Types::PrivatelinkEndpointServiceDataFederationOnlineArchiveAttributes,
      outputs: { id: :id },
      map: [:endpoint_id, :project_id, :provider_name],
      map_present: [:comment, :customer_endpoint_dns_name, :region]
  end
  module Mongodbatlas
    include MongodbatlasPrivatelinkEndpointServiceDataFederationOnlineArchive
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
