# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_api_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasApiKey
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_api_key,
      attributes_class: Mongodbatlas::Types::ApiKeyAttributes,
      outputs: { id: :id },
      map: [:description, :org_id, :role_names]
  end
  module Mongodbatlas
    include MongodbatlasApiKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
