# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class DataLakePipelineAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute :project_id, T::String
    attribute? :sink, T::Array.of(T::Hash).optional
    attribute? :source, T::Array.of(T::Hash).optional
    attribute? :transformations, T::Array.of(T::Hash).optional
  end
end
