# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_x509_authentication_database_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasX509AuthenticationDatabaseUser
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_x509_authentication_database_user,
      attributes_class: Mongodbatlas::Types::X509AuthenticationDatabaseUserAttributes,
      outputs: { id: :id },
      map: [:project_id],
      map_present: [:customer_x509_cas, :months_until_expiration, :username]
  end
  module Mongodbatlas
    include MongodbatlasX509AuthenticationDatabaseUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
