# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class X509AuthenticationDatabaseUserAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :project_id, T::String
    attribute? :customer_x509_cas, T::String.optional
    attribute? :months_until_expiration, T::Float.optional
    attribute? :username, T::String.optional
  end
end
