# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_alert_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasAlertConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_alert_configuration,
      attributes_class: Mongodbatlas::Types::AlertConfigurationAttributes,
      outputs: { id: :id },
      map: [:event_type, :project_id],
      map_present: [:matcher, :metric_threshold_config, :notification, :threshold_config]
  end
  module Mongodbatlas
    include MongodbatlasAlertConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
