# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class AlertConfigurationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :event_type, T::String
    attribute :project_id, T::String
    attribute? :matcher, T::Array.of(T::Hash).optional
    attribute? :metric_threshold_config, T::Array.of(T::Hash).optional
    attribute? :notification, T::Array.of(T::Hash).optional
    attribute? :threshold_config, T::Array.of(T::Hash).optional
  end
end
