# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_search_index/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasSearchIndex
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_search_index,
      attributes_class: Mongodbatlas::Types::SearchIndexAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :collection_name, :database, :name, :project_id],
      map_present: [:analyzer, :analyzers, :fields, :mappings_fields, :search_analyzer, :stored_source, :synonyms, :type],
      map_bool: [:mappings_dynamic, :wait_for_index_build_completion]
  end
  module Mongodbatlas
    include MongodbatlasSearchIndex
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
