# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class SearchIndexAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :cluster_name, T::String
    attribute :collection_name, T::String
    attribute :database, T::String
    attribute :name, T::String
    attribute :project_id, T::String
    attribute? :analyzer, T::String.optional
    attribute? :analyzers, T::String.optional
    attribute? :fields, T::String.optional
    attribute? :mappings_dynamic, T::Bool.optional
    attribute? :mappings_fields, T::String.optional
    attribute? :search_analyzer, T::String.optional
    attribute? :stored_source, T::String.optional
    attribute? :synonyms, T::Array.of(T::Hash).optional
    attribute? :type, T::String.optional
    attribute? :wait_for_index_build_completion, T::Bool.optional
  end
end
