# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_backup_compliance_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasBackupCompliancePolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_backup_compliance_policy,
      attributes_class: Mongodbatlas::Types::BackupCompliancePolicyAttributes,
      outputs: { id: :id },
      map: [:authorized_email, :authorized_user_first_name, :authorized_user_last_name, :project_id],
      map_present: [:on_demand_policy_item, :policy_item_daily, :policy_item_hourly, :policy_item_monthly, :policy_item_weekly, :policy_item_yearly],
      map_bool: [:copy_protection_enabled, :encryption_at_rest_enabled, :pit_enabled]
  end
  module Mongodbatlas
    include MongodbatlasBackupCompliancePolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
