# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class BackupCompliancePolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :authorized_email, T::String
    attribute :authorized_user_first_name, T::String
    attribute :authorized_user_last_name, T::String
    attribute :project_id, T::String
    attribute? :copy_protection_enabled, T::Bool.optional
    attribute? :encryption_at_rest_enabled, T::Bool.optional
    attribute? :on_demand_policy_item, T::Array.of(T::Hash).optional
    attribute? :pit_enabled, T::Bool.optional
    attribute? :policy_item_daily, T::Array.of(T::Hash).optional
    attribute? :policy_item_hourly, T::Array.of(T::Hash).optional
    attribute? :policy_item_monthly, T::Array.of(T::Hash).optional
    attribute? :policy_item_weekly, T::Array.of(T::Hash).optional
    attribute? :policy_item_yearly, T::Array.of(T::Hash).optional
  end
end
