# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_federated_settings_org_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasFederatedSettingsOrgConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_federated_settings_org_config,
      attributes_class: Mongodbatlas::Types::FederatedSettingsOrgConfigAttributes,
      outputs: { id: :id },
      map: [:federation_settings_id, :org_id],
      map_present: [:data_access_identity_provider_ids, :domain_allow_list, :identity_provider_id, :post_auth_role_grants],
      map_bool: [:domain_restriction_enabled]
  end
  module Mongodbatlas
    include MongodbatlasFederatedSettingsOrgConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
