# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class FederatedSettingsOrgConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :domain_restriction_enabled, T::Bool
    attribute :federation_settings_id, T::String
    attribute :org_id, T::String
    attribute? :data_access_identity_provider_ids, T::Array.of(T::String).optional
    attribute? :domain_allow_list, T::Array.of(T::String).optional
    attribute? :identity_provider_id, T::String.optional
    attribute? :post_auth_role_grants, T::Array.of(T::String).optional
  end
end
