# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_federated_settings_org_role_mapping/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasFederatedSettingsOrgRoleMapping
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_federated_settings_org_role_mapping,
      attributes_class: Mongodbatlas::Types::FederatedSettingsOrgRoleMappingAttributes,
      outputs: { id: :id },
      map: [:external_group_name, :federation_settings_id, :org_id, :role_assignments]
  end
  module Mongodbatlas
    include MongodbatlasFederatedSettingsOrgRoleMapping
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
