# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_advanced_cluster/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasAdvancedCluster
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_advanced_cluster,
      attributes_class: Mongodbatlas::Types::AdvancedClusterAttributes,
      outputs: { id: :id },
      map: [:cluster_type, :name, :project_id, :replication_specs],
      map_present: [:accept_data_risks_and_force_replica_set_reconfig, :advanced_configuration, :bi_connector_config, :labels, :pinned_fcv, :tags],
      map_bool: [:delete_on_create_timeout, :retain_backups_enabled]
  end
  module Mongodbatlas
    include MongodbatlasAdvancedCluster
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
