# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_project_invitation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasProjectInvitation
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_project_invitation,
      attributes_class: Mongodbatlas::Types::ProjectInvitationAttributes,
      outputs: { id: :id },
      map: [:project_id, :roles, :username]
  end
  module Mongodbatlas
    include MongodbatlasProjectInvitation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
