# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_third_party_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasThirdPartyIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_third_party_integration,
      attributes_class: Mongodbatlas::Types::ThirdPartyIntegrationAttributes,
      outputs: { id: :id },
      map: [:project_id, :type],
      map_present: [:secret]
  end
  module Mongodbatlas
    include MongodbatlasThirdPartyIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
