# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_ldap_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasLdapConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_ldap_configuration,
      attributes_class: Mongodbatlas::Types::LdapConfigurationAttributes,
      outputs: { id: :id },
      map: [:bind_password, :bind_username, :hostname, :project_id],
      map_present: [:port, :user_to_dn_mapping],
      map_bool: [:authentication_enabled]
  end
  module Mongodbatlas
    include MongodbatlasLdapConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
