# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class LdapConfigurationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :authentication_enabled, T::Bool
    attribute :bind_password, T::String
    attribute :bind_username, T::String
    attribute :hostname, T::String
    attribute :project_id, T::String
    attribute? :port, T::Float.optional
    attribute? :user_to_dn_mapping, T::Array.of(T::Hash).optional
  end
end
