# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_event_trigger/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasEventTrigger
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_event_trigger,
      attributes_class: Mongodbatlas::Types::EventTriggerAttributes,
      outputs: { id: :id },
      map: [:app_id, :name, :project_id, :type],
      map_present: [:event_processors, :function_id]
  end
  module Mongodbatlas
    include MongodbatlasEventTrigger
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
