# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class EventTriggerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :app_id, T::String
    attribute :name, T::String
    attribute :project_id, T::String
    attribute :type, T::String
    attribute? :event_processors, T::Array.of(T::Hash).optional
    attribute? :function_id, T::String.optional
  end
end
