# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_stream_privatelink_endpoint/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasStreamPrivatelinkEndpoint
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_stream_privatelink_endpoint,
      attributes_class: Mongodbatlas::Types::StreamPrivatelinkEndpointAttributes,
      outputs: { id: :id },
      map: [:project_id, :provider_name, :vendor],
      map_present: [:arn, :dns_domain, :dns_sub_domain, :service_endpoint_id]
  end
  module Mongodbatlas
    include MongodbatlasStreamPrivatelinkEndpoint
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
