# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class StreamPrivatelinkEndpointAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :project_id, T::String
    attribute :provider_name, T::String
    attribute :vendor, T::String
    attribute? :arn, T::String.optional
    attribute? :dns_domain, T::String.optional
    attribute? :dns_sub_domain, T::Array.of(T::String).optional
    attribute? :service_endpoint_id, T::String.optional
  end
end
