# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_cluster/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasCluster
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_cluster,
      attributes_class: Mongodbatlas::Types::ClusterAttributes,
      outputs: { id: :id },
      map: [:name, :project_id, :provider_instance_size_name, :provider_name],
      map_present: [:advanced_configuration, :bi_connector_config, :labels, :pinned_fcv, :replication_specs, :tags],
      map_bool: [:retain_backups_enabled]
  end
  module Mongodbatlas
    include MongodbatlasCluster
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
