# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class ClusterAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute :project_id, T::String
    attribute :provider_instance_size_name, T::String
    attribute :provider_name, T::String
    attribute? :advanced_configuration, T::Array.of(T::Hash).optional
    attribute? :bi_connector_config, T::Array.of(T::Hash).optional
    attribute? :labels, T::Array.of(T::Hash).optional
    attribute? :pinned_fcv, T::Array.of(T::Hash).optional
    attribute? :replication_specs, T::Array.of(T::Hash).optional
    attribute? :retain_backups_enabled, T::Bool.optional
    attribute? :tags, T::Array.of(T::Hash).optional
  end
end
