# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_cloud_backup_schedule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasCloudBackupSchedule
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_cloud_backup_schedule,
      attributes_class: Mongodbatlas::Types::CloudBackupScheduleAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :project_id],
      map_present: [:copy_settings, :export, :policy_item_daily, :policy_item_hourly, :policy_item_monthly, :policy_item_weekly, :policy_item_yearly]
  end
  module Mongodbatlas
    include MongodbatlasCloudBackupSchedule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
