# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class CloudBackupScheduleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :cluster_name, T::String
    attribute :project_id, T::String
    attribute? :copy_settings, T::Array.of(T::Hash).optional
    attribute? :export, T::Array.of(T::Hash).optional
    attribute? :policy_item_daily, T::Array.of(T::Hash).optional
    attribute? :policy_item_hourly, T::Array.of(T::Hash).optional
    attribute? :policy_item_monthly, T::Array.of(T::Hash).optional
    attribute? :policy_item_weekly, T::Array.of(T::Hash).optional
    attribute? :policy_item_yearly, T::Array.of(T::Hash).optional
  end
end
