# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_cloud_provider_access_authorization/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasCloudProviderAccessAuthorization
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_cloud_provider_access_authorization,
      attributes_class: Mongodbatlas::Types::CloudProviderAccessAuthorizationAttributes,
      outputs: { id: :id },
      map: [:project_id, :role_id],
      map_present: [:aws, :azure]
  end
  module Mongodbatlas
    include MongodbatlasCloudProviderAccessAuthorization
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
