# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_encryption_at_rest/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasEncryptionAtRest
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_encryption_at_rest,
      attributes_class: Mongodbatlas::Types::EncryptionAtRestAttributes,
      outputs: { id: :id },
      map: [:project_id],
      map_present: [:aws_kms_config, :azure_key_vault_config, :google_cloud_kms_config]
  end
  module Mongodbatlas
    include MongodbatlasEncryptionAtRest
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
