# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class EncryptionAtRestAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :project_id, T::String
    attribute? :aws_kms_config, T::Array.of(T::Hash).optional
    attribute? :azure_key_vault_config, T::Array.of(T::Hash).optional
    attribute? :google_cloud_kms_config, T::Array.of(T::Hash).optional
  end
end
