# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class CloudBackupSnapshotRestoreJobAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :cluster_name, T::String
    attribute :project_id, T::String
    attribute? :delivery_type_config, T::Array.of(T::Hash).optional
    attribute? :snapshot_id, T::String.optional
  end
end
