# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_maintenance_window/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasMaintenanceWindow
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_maintenance_window,
      attributes_class: Mongodbatlas::Types::MaintenanceWindowAttributes,
      outputs: { id: :id },
      map: [:day_of_week, :project_id],
      map_present: [:protected_hours]
  end
  module Mongodbatlas
    include MongodbatlasMaintenanceWindow
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
