# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_cloud_backup_snapshot_export_bucket/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasCloudBackupSnapshotExportBucket
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_cloud_backup_snapshot_export_bucket,
      attributes_class: Mongodbatlas::Types::CloudBackupSnapshotExportBucketAttributes,
      outputs: { id: :id },
      map: [:bucket_name, :cloud_provider, :project_id],
      map_present: [:iam_role_id, :role_id, :service_url]
  end
  module Mongodbatlas
    include MongodbatlasCloudBackupSnapshotExportBucket
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
