# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class CloudBackupSnapshotExportBucketAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :bucket_name, T::String
    attribute :cloud_provider, T::String
    attribute :project_id, T::String
    attribute? :iam_role_id, T::String.optional
    attribute? :role_id, T::String.optional
    attribute? :service_url, T::String.optional
  end
end
