# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_privatelink_endpoint_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasPrivatelinkEndpointService
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_privatelink_endpoint_service,
      attributes_class: Mongodbatlas::Types::PrivatelinkEndpointServiceAttributes,
      outputs: { id: :id },
      map: [:endpoint_service_id, :private_link_id, :project_id, :provider_name],
      map_present: [:endpoints, :gcp_project_id]
  end
  module Mongodbatlas
    include MongodbatlasPrivatelinkEndpointService
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
