# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class PrivatelinkEndpointServiceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :endpoint_service_id, T::String
    attribute :private_link_id, T::String
    attribute :project_id, T::String
    attribute :provider_name, T::String
    attribute? :endpoints, T::Array.of(T::Hash).optional
    attribute? :gcp_project_id, T::String.optional
  end
end
