# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_stream_connection/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasStreamConnection
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_stream_connection,
      attributes_class: Mongodbatlas::Types::StreamConnectionAttributes,
      outputs: { id: :id },
      map: [:connection_name, :instance_name, :project_id, :type],
      map_present: [:authentication, :aws, :bootstrap_servers, :cluster_name, :cluster_project_id, :config, :db_role_to_execute, :headers, :security, :url]
  end
  module Mongodbatlas
    include MongodbatlasStreamConnection
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
