# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class StreamConnectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :connection_name, T::String
    attribute :instance_name, T::String
    attribute :project_id, T::String
    attribute :type, T::String
    attribute? :authentication, T::Hash.optional
    attribute? :aws, T::Hash.optional
    attribute? :bootstrap_servers, T::String.optional
    attribute? :cluster_name, T::String.optional
    attribute? :cluster_project_id, T::String.optional
    attribute? :config, T::Hash.optional
    attribute? :db_role_to_execute, T::Hash.optional
    attribute? :headers, T::Hash.optional
    attribute? :security, T::Hash.optional
    attribute? :url, T::String.optional
  end
end
