# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_network_container/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasNetworkContainer
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_network_container,
      attributes_class: Mongodbatlas::Types::NetworkContainerAttributes,
      outputs: { id: :id },
      map: [:atlas_cidr_block, :project_id],
      map_present: [:provider_name]
  end
  module Mongodbatlas
    include MongodbatlasNetworkContainer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
