# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_search_deployment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasSearchDeployment
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_search_deployment,
      attributes_class: Mongodbatlas::Types::SearchDeploymentAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :project_id, :specs],
      map_present: [:timeouts],
      map_bool: [:delete_on_create_timeout, :skip_wait_on_update]
  end
  module Mongodbatlas
    include MongodbatlasSearchDeployment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
