# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class SearchDeploymentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :cluster_name, T::String
    attribute :project_id, T::String
    attribute :specs, T::Array.of(T::Hash)
    attribute? :delete_on_create_timeout, T::Bool.optional
    attribute? :skip_wait_on_update, T::Bool.optional
    attribute? :timeouts, T::Hash.optional
  end
end
