# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_project/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasProject
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_project,
      attributes_class: Mongodbatlas::Types::ProjectAttributes,
      outputs: { id: :id },
      map: [:name, :org_id],
      map_present: [:limits, :project_owner_id, :tags, :teams]
  end
  module Mongodbatlas
    include MongodbatlasProject
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
