# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class ProjectAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute :org_id, T::String
    attribute? :limits, T::Array.of(T::Hash).optional
    attribute? :project_owner_id, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :teams, T::Array.of(T::Hash).optional
  end
end
