# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_org_invitation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasOrgInvitation
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_org_invitation,
      attributes_class: Mongodbatlas::Types::OrgInvitationAttributes,
      outputs: { id: :id },
      map: [:org_id, :roles, :username]
  end
  module Mongodbatlas
    include MongodbatlasOrgInvitation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
