# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_cloud_backup_snapshot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasCloudBackupSnapshot
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_cloud_backup_snapshot,
      attributes_class: Mongodbatlas::Types::CloudBackupSnapshotAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :description, :project_id, :retention_in_days]
  end
  module Mongodbatlas
    include MongodbatlasCloudBackupSnapshot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
