# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_push_based_log_export/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasPushBasedLogExport
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_push_based_log_export,
      attributes_class: Mongodbatlas::Types::PushBasedLogExportAttributes,
      outputs: { id: :id },
      map: [:bucket_name, :iam_role_id, :project_id],
      map_present: [:timeouts]
  end
  module Mongodbatlas
    include MongodbatlasPushBasedLogExport
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
