# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_access_list_api_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasAccessListApiKey
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_access_list_api_key,
      attributes_class: Mongodbatlas::Types::AccessListApiKeyAttributes,
      outputs: { id: :id },
      map: [:api_key_id, :org_id]
  end
  module Mongodbatlas
    include MongodbatlasAccessListApiKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
