# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_online_archive/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasOnlineArchive
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_online_archive,
      attributes_class: Mongodbatlas::Types::OnlineArchiveAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :coll_name, :criteria, :db_name, :project_id],
      map_present: [:data_expiration_rule, :data_process_region, :partition_fields, :schedule],
      map_bool: [:sync_creation]
  end
  module Mongodbatlas
    include MongodbatlasOnlineArchive
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
