# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class OnlineArchiveAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :cluster_name, T::String
    attribute :coll_name, T::String
    attribute :criteria, T::Array.of(T::Hash)
    attribute :db_name, T::String
    attribute :project_id, T::String
    attribute? :data_expiration_rule, T::Array.of(T::Hash).optional
    attribute? :data_process_region, T::Array.of(T::Hash).optional
    attribute? :partition_fields, T::Array.of(T::Hash).optional
    attribute? :schedule, T::Array.of(T::Hash).optional
    attribute? :sync_creation, T::Bool.optional
  end
end
