# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class LdapVerifyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :bind_password, T::String
    attribute :bind_username, T::String
    attribute :hostname, T::String
    attribute :port, T::Float
    attribute :project_id, T::String
  end
end
