# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_organization/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasOrganization
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_organization,
      attributes_class: Mongodbatlas::Types::OrganizationAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :federation_settings_id, :org_owner_id, :role_names, :security_contact],
      map_bool: [:gen_ai_features_enabled]
  end
  module Mongodbatlas
    include MongodbatlasOrganization
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
