# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class OrganizationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :federation_settings_id, T::String.optional
    attribute? :gen_ai_features_enabled, T::Bool.optional
    attribute? :org_owner_id, T::String.optional
    attribute? :role_names, T::Array.of(T::String).optional
    attribute? :security_contact, T::String.optional
  end
end
