# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_auditing/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasAuditing
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_auditing,
      attributes_class: Mongodbatlas::Types::AuditingAttributes,
      outputs: { id: :id },
      map: [:project_id]
  end
  module Mongodbatlas
    include MongodbatlasAuditing
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
