# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_federated_database_instance/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasFederatedDatabaseInstance
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_federated_database_instance,
      attributes_class: Mongodbatlas::Types::FederatedDatabaseInstanceAttributes,
      outputs: { id: :id },
      map: [:name, :project_id],
      map_present: [:cloud_provider_config, :data_process_region, :storage_databases, :storage_stores]
  end
  module Mongodbatlas
    include MongodbatlasFederatedDatabaseInstance
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
