# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class FederatedDatabaseInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute :project_id, T::String
    attribute? :cloud_provider_config, T::Array.of(T::Hash).optional
    attribute? :data_process_region, T::Array.of(T::Hash).optional
    attribute? :storage_databases, T::Array.of(T::Hash).optional
    attribute? :storage_stores, T::Array.of(T::Hash).optional
  end
end
