# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_flex_cluster/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasFlexCluster
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_flex_cluster,
      attributes_class: Mongodbatlas::Types::FlexClusterAttributes,
      outputs: { id: :id },
      map: [:name, :project_id, :provider_settings],
      map_present: [:tags]
  end
  module Mongodbatlas
    include MongodbatlasFlexCluster
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
