# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class FlexClusterAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute :project_id, T::String
    attribute :provider_settings, T::Hash
    attribute? :tags, T::Hash.optional
  end
end
