# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_federated_query_limit/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasFederatedQueryLimit
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_federated_query_limit,
      attributes_class: Mongodbatlas::Types::FederatedQueryLimitAttributes,
      outputs: { id: :id },
      map: [:limit_name, :overrun_policy, :project_id, :tenant_name, :value],
      map_present: [:default_limit, :maximum_limit]
  end
  module Mongodbatlas
    include MongodbatlasFederatedQueryLimit
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
