# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class FederatedQueryLimitAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :limit_name, T::String
    attribute :overrun_policy, T::String
    attribute :project_id, T::String
    attribute :tenant_name, T::String
    attribute :value, T::Float
    attribute? :default_limit, T::Float.optional
    attribute? :maximum_limit, T::Float.optional
  end
end
