# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_private_endpoint_regional_mode/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasPrivateEndpointRegionalMode
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_private_endpoint_regional_mode,
      attributes_class: Mongodbatlas::Types::PrivateEndpointRegionalModeAttributes,
      outputs: { id: :id },
      map: [:project_id]
  end
  module Mongodbatlas
    include MongodbatlasPrivateEndpointRegionalMode
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
