# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_stream_instance/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasStreamInstance
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_stream_instance,
      attributes_class: Mongodbatlas::Types::StreamInstanceAttributes,
      outputs: { id: :id },
      map: [:data_process_region, :instance_name, :project_id]
  end
  module Mongodbatlas
    include MongodbatlasStreamInstance
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
