# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_serverless_instance/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasServerlessInstance
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_serverless_instance,
      attributes_class: Mongodbatlas::Types::ServerlessInstanceAttributes,
      outputs: { id: :id },
      map: [:name, :project_id, :provider_settings_backing_provider_name, :provider_settings_provider_name, :provider_settings_region_name],
      map_present: [:links, :tags]
  end
  module Mongodbatlas
    include MongodbatlasServerlessInstance
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
