# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class ServerlessInstanceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :name, T::String
    attribute :project_id, T::String
    attribute :provider_settings_backing_provider_name, T::String
    attribute :provider_settings_provider_name, T::String
    attribute :provider_settings_region_name, T::String
    attribute? :links, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::Hash).optional
  end
end
