# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_privatelink_endpoint_service_serverless/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasPrivatelinkEndpointServiceServerless
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_privatelink_endpoint_service_serverless,
      attributes_class: Mongodbatlas::Types::PrivatelinkEndpointServiceServerlessAttributes,
      outputs: { id: :id },
      map: [:endpoint_id, :instance_name, :project_id, :provider_name],
      map_present: [:comment]
  end
  module Mongodbatlas
    include MongodbatlasPrivatelinkEndpointServiceServerless
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
