# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class PrivatelinkEndpointServiceServerlessAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :endpoint_id, T::String
    attribute :instance_name, T::String
    attribute :project_id, T::String
    attribute :provider_name, T::String
    attribute? :comment, T::String.optional
  end
end
