# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_mongodb_employee_access_grant/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasMongodbEmployeeAccessGrant
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_mongodb_employee_access_grant,
      attributes_class: Mongodbatlas::Types::MongodbEmployeeAccessGrantAttributes,
      outputs: { id: :id },
      map: [:cluster_name, :expiration_time, :grant_type, :project_id]
  end
  module Mongodbatlas
    include MongodbatlasMongodbEmployeeAccessGrant
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
