# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_database_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasDatabaseUser
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_database_user,
      attributes_class: Mongodbatlas::Types::DatabaseUserAttributes,
      outputs: { id: :id },
      map: [:auth_database_name, :project_id, :username],
      map_present: [:description, :labels, :password, :roles, :scopes]
  end
  module Mongodbatlas
    include MongodbatlasDatabaseUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
