# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class DatabaseUserAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :auth_database_name, T::String
    attribute :project_id, T::String
    attribute :username, T::String
    attribute? :description, T::String.optional
    attribute? :labels, T::Array.of(T::Hash).optional
    attribute? :password, T::String.optional
    attribute? :roles, T::Array.of(T::Hash).optional
    attribute? :scopes, T::Array.of(T::Hash).optional
  end
end
