# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_custom_db_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasCustomDbRole
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_custom_db_role,
      attributes_class: Mongodbatlas::Types::CustomDbRoleAttributes,
      outputs: { id: :id },
      map: [:project_id, :role_name],
      map_present: [:actions, :inherited_roles]
  end
  module Mongodbatlas
    include MongodbatlasCustomDbRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
