# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Mongodbatlas::Types
  include Dry.Types()

  class CustomDbRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Mongodbatlas::Types

    attribute :project_id, T::String
    attribute :role_name, T::String
    attribute? :actions, T::Array.of(T::Hash).optional
    attribute? :inherited_roles, T::Array.of(T::Hash).optional
  end
end
