# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/mongodbatlas_federated_settings_identity_provider/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module MongodbatlasFederatedSettingsIdentityProvider
    include Pangea::Resources::ResourceBuilder

    define_resource :mongodbatlas_federated_settings_identity_provider,
      attributes_class: Mongodbatlas::Types::FederatedSettingsIdentityProviderAttributes,
      outputs: { id: :id },
      map: [:federation_settings_id, :issuer_uri, :name],
      map_present: [:associated_domains, :audience, :authorization_type, :client_id, :description, :groups_claim, :request_binding, :requested_scopes, :response_signature_algorithm, :sso_url, :status, :user_claim],
      map_bool: [:sso_debug_enabled]
  end
  module Mongodbatlas
    include MongodbatlasFederatedSettingsIdentityProvider
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Mongodbatlas)
