# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_federated_settings_identity_provider resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasFederatedSettingsIdentityProvider do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { federation_settings_id: 'test-value', issuer_uri: 'test-value', name: 'test-value' } }

  describe ':mongodbatlas_federated_settings_identity_provider' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'test')
        validate_required_attributes(config, [:federation_settings_id, :issuer_uri, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_settings_identity_provider('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_federated_settings_identity_provider)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_settings_identity_provider('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_federated_settings_identity_provider.test.id}")
        expect(ref.idp_id).to eq("${mongodbatlas_federated_settings_identity_provider.test.idp_id}")
        expect(ref.idp_type).to eq("${mongodbatlas_federated_settings_identity_provider.test.idp_type}")
        expect(ref.okta_idp_id).to eq("${mongodbatlas_federated_settings_identity_provider.test.okta_idp_id}")
        expect(ref.protocol).to eq("${mongodbatlas_federated_settings_identity_provider.test.protocol}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'test')
        expect(config).not_to have_key('idp_id')
        expect(config).not_to have_key('idp_type')
        expect(config).not_to have_key('okta_idp_id')
        expect(config).not_to have_key('protocol')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ associated_domains: ['test-value'], audience: 'test-value', authorization_type: 'test-value', client_id: 'test-value', description: 'test-value', groups_claim: 'test-value', request_binding: 'test-value', requested_scopes: ['test-value'], response_signature_algorithm: 'test-value', sso_debug_enabled: true, sso_url: 'test-value', status: 'test-value', user_claim: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'full')
        expect(config).to have_key('associated_domains')
        expect(config).to have_key('audience')
        expect(config).to have_key('authorization_type')
        expect(config).to have_key('client_id')
        expect(config).to have_key('description')
        expect(config).to have_key('groups_claim')
        expect(config).to have_key('request_binding')
        expect(config).to have_key('requested_scopes')
        expect(config).to have_key('response_signature_algorithm')
        expect(config).to have_key('sso_debug_enabled')
        expect(config).to have_key('sso_url')
        expect(config).to have_key('status')
        expect(config).to have_key('user_claim')
      end
    end

    context 'optional attributes' do
      it 'includes associated_domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(associated_domains: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('associated_domains')
      end

      it 'omits associated_domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('associated_domains')
      end
      it 'includes audience when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(audience: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('audience')
      end

      it 'omits audience when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('audience')
      end
      it 'includes authorization_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(authorization_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('authorization_type')
      end

      it 'omits authorization_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('authorization_type')
      end
      it 'includes client_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(client_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('client_id')
      end

      it 'omits client_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('client_id')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes groups_claim when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(groups_claim: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('groups_claim')
      end

      it 'omits groups_claim when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('groups_claim')
      end
      it 'includes request_binding when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(request_binding: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('request_binding')
      end

      it 'omits request_binding when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('request_binding')
      end
      it 'includes requested_scopes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(requested_scopes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('requested_scopes')
      end

      it 'omits requested_scopes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('requested_scopes')
      end
      it 'includes response_signature_algorithm when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(response_signature_algorithm: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('response_signature_algorithm')
      end

      it 'omits response_signature_algorithm when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('response_signature_algorithm')
      end
      it 'includes sso_debug_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(sso_debug_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('sso_debug_enabled')
      end

      it 'omits sso_debug_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('sso_debug_enabled')
      end
      it 'includes sso_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(sso_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('sso_url')
      end

      it 'omits sso_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('sso_url')
      end
      it 'includes status when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(status: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('status')
      end

      it 'omits status when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('status')
      end
      it 'includes user_claim when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('opt', required_attrs.merge(user_claim: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'opt')
        expect(config).to have_key('user_claim')
      end

      it 'omits user_claim when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'minimal')
        expect(config).not_to have_key('user_claim')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts sso_debug_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(sso_debug_enabled: val)
          synth.mongodbatlas_federated_settings_identity_provider("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', "bool_#{val}")
          expect(config['sso_debug_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_identity_provider', 'typed')
        expect(config['federation_settings_id']).to be_a(String)
        expect(config['issuer_uri']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_identity_provider('first', required_attrs)
        synth.mongodbatlas_federated_settings_identity_provider('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_federated_settings_identity_provider')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_federated_settings_identity_provider,
    method: :mongodbatlas_federated_settings_identity_provider,
    required_attrs: { federation_settings_id: 'test-value', issuer_uri: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :idp_id, :idp_type, :okta_idp_id, :protocol],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:sso_debug_enabled]
end
