# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_federated_settings_org_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasFederatedSettingsOrgConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain_restriction_enabled: true, federation_settings_id: 'test-value', org_id: 'test-value' } }

  describe ':mongodbatlas_federated_settings_org_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'test')
        validate_required_attributes(config, [:domain_restriction_enabled, :federation_settings_id, :org_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_settings_org_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_federated_settings_org_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_settings_org_config('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_federated_settings_org_config.test.id}")
        expect(ref.user_conflicts).to eq("${mongodbatlas_federated_settings_org_config.test.user_conflicts}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'test')
        expect(config).not_to have_key('user_conflicts')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_access_identity_provider_ids: ['test-value'], domain_allow_list: ['test-value'], identity_provider_id: 'test-value', post_auth_role_grants: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'full')
        expect(config).to have_key('data_access_identity_provider_ids')
        expect(config).to have_key('domain_allow_list')
        expect(config).to have_key('identity_provider_id')
        expect(config).to have_key('post_auth_role_grants')
      end
    end

    context 'optional attributes' do
      it 'includes data_access_identity_provider_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('opt', required_attrs.merge(data_access_identity_provider_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'opt')
        expect(config).to have_key('data_access_identity_provider_ids')
      end

      it 'omits data_access_identity_provider_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'minimal')
        expect(config).not_to have_key('data_access_identity_provider_ids')
      end
      it 'includes domain_allow_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('opt', required_attrs.merge(domain_allow_list: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'opt')
        expect(config).to have_key('domain_allow_list')
      end

      it 'omits domain_allow_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'minimal')
        expect(config).not_to have_key('domain_allow_list')
      end
      it 'includes identity_provider_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('opt', required_attrs.merge(identity_provider_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'opt')
        expect(config).to have_key('identity_provider_id')
      end

      it 'omits identity_provider_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'minimal')
        expect(config).not_to have_key('identity_provider_id')
      end
      it 'includes post_auth_role_grants when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('opt', required_attrs.merge(post_auth_role_grants: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'opt')
        expect(config).to have_key('post_auth_role_grants')
      end

      it 'omits post_auth_role_grants when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'minimal')
        expect(config).not_to have_key('post_auth_role_grants')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts domain_restriction_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(domain_restriction_enabled: val)
          synth.mongodbatlas_federated_settings_org_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', "bool_#{val}")
          expect(config['domain_restriction_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_config', 'typed')
        expect([true, false]).to include(config['domain_restriction_enabled'])
        expect(config['federation_settings_id']).to be_a(String)
        expect(config['org_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_config('first', required_attrs)
        synth.mongodbatlas_federated_settings_org_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_federated_settings_org_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_federated_settings_org_config,
    method: :mongodbatlas_federated_settings_org_config,
    required_attrs: { domain_restriction_enabled: true, federation_settings_id: 'test-value', org_id: 'test-value' },
    expected_outputs: [:id, :user_conflicts],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:domain_restriction_enabled]
end
