# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_network_container resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasNetworkContainer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { atlas_cidr_block: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_network_container' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_network_container', 'test')
        validate_required_attributes(config, [:atlas_cidr_block, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_network_container('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_network_container)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_network_container('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_network_container.test.id}")
        expect(ref.azure_subscription_id).to eq("${mongodbatlas_network_container.test.azure_subscription_id}")
        expect(ref.container_id).to eq("${mongodbatlas_network_container.test.container_id}")
        expect(ref.gcp_project_id).to eq("${mongodbatlas_network_container.test.gcp_project_id}")
        expect(ref.network_name).to eq("${mongodbatlas_network_container.test.network_name}")
        expect(ref.provisioned).to eq("${mongodbatlas_network_container.test.provisioned}")
        expect(ref.region).to eq("${mongodbatlas_network_container.test.region}")
        expect(ref.region_name).to eq("${mongodbatlas_network_container.test.region_name}")
        expect(ref.regions).to eq("${mongodbatlas_network_container.test.regions}")
        expect(ref.vnet_name).to eq("${mongodbatlas_network_container.test.vnet_name}")
        expect(ref.vpc_id).to eq("${mongodbatlas_network_container.test.vpc_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_network_container', 'test')
        expect(config).not_to have_key('azure_subscription_id')
        expect(config).not_to have_key('container_id')
        expect(config).not_to have_key('gcp_project_id')
        expect(config).not_to have_key('network_name')
        expect(config).not_to have_key('provisioned')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('region_name')
        expect(config).not_to have_key('regions')
        expect(config).not_to have_key('vnet_name')
        expect(config).not_to have_key('vpc_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ provider_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_network_container', 'full')
        expect(config).to have_key('provider_name')
      end
    end

    context 'optional attributes' do
      it 'includes provider_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('opt', required_attrs.merge(provider_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_network_container', 'opt')
        expect(config).to have_key('provider_name')
      end

      it 'omits provider_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_network_container', 'minimal')
        expect(config).not_to have_key('provider_name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_network_container', 'typed')
        expect(config['atlas_cidr_block']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_container('first', required_attrs)
        synth.mongodbatlas_network_container('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_network_container')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_network_container,
    method: :mongodbatlas_network_container,
    required_attrs: { atlas_cidr_block: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :azure_subscription_id, :container_id, :gcp_project_id, :network_name, :provisioned, :region, :region_name, :regions, :vnet_name, :vpc_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
