# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_mongodb_employee_access_grant resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasMongodbEmployeeAccessGrant do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', expiration_time: 'test-value', grant_type: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_mongodb_employee_access_grant' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_mongodb_employee_access_grant('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_mongodb_employee_access_grant', 'test')
        validate_required_attributes(config, [:cluster_name, :expiration_time, :grant_type, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_mongodb_employee_access_grant('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_mongodb_employee_access_grant)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_mongodb_employee_access_grant('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_mongodb_employee_access_grant.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_mongodb_employee_access_grant('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_mongodb_employee_access_grant', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['expiration_time']).to be_a(String)
        expect(config['grant_type']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_mongodb_employee_access_grant('first', required_attrs)
        synth.mongodbatlas_mongodb_employee_access_grant('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_mongodb_employee_access_grant')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_mongodb_employee_access_grant,
    method: :mongodbatlas_mongodb_employee_access_grant,
    required_attrs: { cluster_name: 'test-value', expiration_time: 'test-value', grant_type: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
