# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_serverless_instance resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasServerlessInstance do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project_id: 'test-value', provider_settings_backing_provider_name: 'test-value', provider_settings_provider_name: 'test-value', provider_settings_region_name: 'test-value' } }

  describe ':mongodbatlas_serverless_instance' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'test')
        validate_required_attributes(config, [:name, :project_id, :provider_settings_backing_provider_name, :provider_settings_provider_name, :provider_settings_region_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_serverless_instance('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_serverless_instance)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_serverless_instance('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_serverless_instance.test.id}")
        expect(ref.auto_indexing).to eq("${mongodbatlas_serverless_instance.test.auto_indexing}")
        expect(ref.connection_strings_private_endpoint_srv).to eq("${mongodbatlas_serverless_instance.test.connection_strings_private_endpoint_srv}")
        expect(ref.connection_strings_standard_srv).to eq("${mongodbatlas_serverless_instance.test.connection_strings_standard_srv}")
        expect(ref.continuous_backup_enabled).to eq("${mongodbatlas_serverless_instance.test.continuous_backup_enabled}")
        expect(ref.create_date).to eq("${mongodbatlas_serverless_instance.test.create_date}")
        expect(ref.mongo_db_version).to eq("${mongodbatlas_serverless_instance.test.mongo_db_version}")
        expect(ref.state_name).to eq("${mongodbatlas_serverless_instance.test.state_name}")
        expect(ref.termination_protection_enabled).to eq("${mongodbatlas_serverless_instance.test.termination_protection_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'test')
        expect(config).not_to have_key('auto_indexing')
        expect(config).not_to have_key('connection_strings_private_endpoint_srv')
        expect(config).not_to have_key('connection_strings_standard_srv')
        expect(config).not_to have_key('continuous_backup_enabled')
        expect(config).not_to have_key('create_date')
        expect(config).not_to have_key('mongo_db_version')
        expect(config).not_to have_key('state_name')
        expect(config).not_to have_key('termination_protection_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ links: [{ 'key1' => 'val1' }], tags: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'full')
        expect(config).to have_key('links')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes links when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('opt', required_attrs.merge(links: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'opt')
        expect(config).to have_key('links')
      end

      it 'omits links when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'minimal')
        expect(config).not_to have_key('links')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('opt', required_attrs.merge(tags: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_serverless_instance', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_settings_backing_provider_name']).to be_a(String)
        expect(config['provider_settings_provider_name']).to be_a(String)
        expect(config['provider_settings_region_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_serverless_instance('first', required_attrs)
        synth.mongodbatlas_serverless_instance('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_serverless_instance')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_serverless_instance,
    method: :mongodbatlas_serverless_instance,
    required_attrs: { name: 'test-value', project_id: 'test-value', provider_settings_backing_provider_name: 'test-value', provider_settings_provider_name: 'test-value', provider_settings_region_name: 'test-value' },
    expected_outputs: [:id, :auto_indexing, :connection_strings_private_endpoint_srv, :connection_strings_standard_srv, :continuous_backup_enabled, :create_date, :mongo_db_version, :state_name, :termination_protection_enabled],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
