# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_global_cluster_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasGlobalClusterConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_global_cluster_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'test')
        validate_required_attributes(config, [:cluster_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_global_cluster_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_global_cluster_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_global_cluster_config('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_global_cluster_config.test.id}")
        expect(ref.custom_zone_mapping).to eq("${mongodbatlas_global_cluster_config.test.custom_zone_mapping}")
        expect(ref.custom_zone_mapping_zone_id).to eq("${mongodbatlas_global_cluster_config.test.custom_zone_mapping_zone_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'test')
        expect(config).not_to have_key('custom_zone_mapping')
        expect(config).not_to have_key('custom_zone_mapping_zone_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_zone_mappings: [{ 'key1' => 'val1' }], managed_namespaces: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'full')
        expect(config).to have_key('custom_zone_mappings')
        expect(config).to have_key('managed_namespaces')
      end
    end

    context 'optional attributes' do
      it 'includes custom_zone_mappings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('opt', required_attrs.merge(custom_zone_mappings: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'opt')
        expect(config).to have_key('custom_zone_mappings')
      end

      it 'omits custom_zone_mappings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'minimal')
        expect(config).not_to have_key('custom_zone_mappings')
      end
      it 'includes managed_namespaces when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('opt', required_attrs.merge(managed_namespaces: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'opt')
        expect(config).to have_key('managed_namespaces')
      end

      it 'omits managed_namespaces when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'minimal')
        expect(config).not_to have_key('managed_namespaces')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_global_cluster_config', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_global_cluster_config('first', required_attrs)
        synth.mongodbatlas_global_cluster_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_global_cluster_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_global_cluster_config,
    method: :mongodbatlas_global_cluster_config,
    required_attrs: { cluster_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :custom_zone_mapping, :custom_zone_mapping_zone_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
