# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_stream_processor resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasStreamProcessor do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { instance_name: 'test-value', pipeline: 'test-value', processor_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_stream_processor' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_stream_processor', 'test')
        validate_required_attributes(config, [:instance_name, :pipeline, :processor_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_processor('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_stream_processor)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_processor('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_stream_processor.test.id}")
        expect(ref.state).to eq("${mongodbatlas_stream_processor.test.state}")
        expect(ref.stats).to eq("${mongodbatlas_stream_processor.test.stats}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_processor', 'test')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('stats')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ options: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_processor', 'full')
        expect(config).to have_key('options')
      end
    end

    context 'optional attributes' do
      it 'includes options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('opt', required_attrs.merge(options: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_processor', 'opt')
        expect(config).to have_key('options')
      end

      it 'omits options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_processor', 'minimal')
        expect(config).not_to have_key('options')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_processor', 'typed')
        expect(config['instance_name']).to be_a(String)
        expect(config['pipeline']).to be_a(String)
        expect(config['processor_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_processor('first', required_attrs)
        synth.mongodbatlas_stream_processor('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_stream_processor')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_stream_processor,
    method: :mongodbatlas_stream_processor,
    required_attrs: { instance_name: 'test-value', pipeline: 'test-value', processor_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :state, :stats],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
