# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_x509_authentication_database_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasX509AuthenticationDatabaseUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value' } }

  describe ':mongodbatlas_x509_authentication_database_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'test')
        validate_required_attributes(config, [:project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_x509_authentication_database_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_x509_authentication_database_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_x509_authentication_database_user('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_x509_authentication_database_user.test.id}")
        expect(ref.certificates).to eq("${mongodbatlas_x509_authentication_database_user.test.certificates}")
        expect(ref.current_certificate).to eq("${mongodbatlas_x509_authentication_database_user.test.current_certificate}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'test')
        expect(config).not_to have_key('certificates')
        expect(config).not_to have_key('current_certificate')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ customer_x509_cas: 'test-value', months_until_expiration: 3.14, username: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'full')
        expect(config).to have_key('customer_x509_cas')
        expect(config).to have_key('months_until_expiration')
        expect(config).to have_key('username')
      end
    end

    context 'optional attributes' do
      it 'includes customer_x509_cas when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('opt', required_attrs.merge(customer_x509_cas: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'opt')
        expect(config).to have_key('customer_x509_cas')
      end

      it 'omits customer_x509_cas when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'minimal')
        expect(config).not_to have_key('customer_x509_cas')
      end
      it 'includes months_until_expiration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('opt', required_attrs.merge(months_until_expiration: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'opt')
        expect(config).to have_key('months_until_expiration')
      end

      it 'omits months_until_expiration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'minimal')
        expect(config).not_to have_key('months_until_expiration')
      end
      it 'includes username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('opt', required_attrs.merge(username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'opt')
        expect(config).to have_key('username')
      end

      it 'omits username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'minimal')
        expect(config).not_to have_key('username')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:current_certificate, :customer_x509_cas]
        expect(sensitive_fields).to include(:current_certificate)
        expect(sensitive_fields).to include(:customer_x509_cas)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_x509_authentication_database_user', 'typed')
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_x509_authentication_database_user('first', required_attrs)
        synth.mongodbatlas_x509_authentication_database_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_x509_authentication_database_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_x509_authentication_database_user,
    method: :mongodbatlas_x509_authentication_database_user,
    required_attrs: { project_id: 'test-value' },
    expected_outputs: [:id, :certificates, :current_certificate],
    sensitive_fields: [:current_certificate, :customer_x509_cas],
    immutable_fields: [],
    boolean_fields: []
end
