# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cloud_provider_access_authorization resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCloudProviderAccessAuthorization do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value', role_id: 'test-value' } }

  describe ':mongodbatlas_cloud_provider_access_authorization' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'test')
        validate_required_attributes(config, [:project_id, :role_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_provider_access_authorization('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cloud_provider_access_authorization)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_provider_access_authorization('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cloud_provider_access_authorization.test.id}")
        expect(ref.authorized_date).to eq("${mongodbatlas_cloud_provider_access_authorization.test.authorized_date}")
        expect(ref.feature_usages).to eq("${mongodbatlas_cloud_provider_access_authorization.test.feature_usages}")
        expect(ref.gcp).to eq("${mongodbatlas_cloud_provider_access_authorization.test.gcp}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'test')
        expect(config).not_to have_key('authorized_date')
        expect(config).not_to have_key('feature_usages')
        expect(config).not_to have_key('gcp')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ aws: [{ 'key1' => 'val1' }], azure: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'full')
        expect(config).to have_key('aws')
        expect(config).to have_key('azure')
      end
    end

    context 'optional attributes' do
      it 'includes aws when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('opt', required_attrs.merge(aws: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'opt')
        expect(config).to have_key('aws')
      end

      it 'omits aws when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'minimal')
        expect(config).not_to have_key('aws')
      end
      it 'includes azure when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('opt', required_attrs.merge(azure: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'opt')
        expect(config).to have_key('azure')
      end

      it 'omits azure when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'minimal')
        expect(config).not_to have_key('azure')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_authorization', 'typed')
        expect(config['project_id']).to be_a(String)
        expect(config['role_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_authorization('first', required_attrs)
        synth.mongodbatlas_cloud_provider_access_authorization('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cloud_provider_access_authorization')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cloud_provider_access_authorization,
    method: :mongodbatlas_cloud_provider_access_authorization,
    required_attrs: { project_id: 'test-value', role_id: 'test-value' },
    expected_outputs: [:id, :authorized_date, :feature_usages, :gcp],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
