# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_project_ip_access_list resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasProjectIpAccessList do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value' } }

  describe ':mongodbatlas_project_ip_access_list' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_project_ip_access_list', 'test')
        validate_required_attributes(config, [:project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_project_ip_access_list('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_project_ip_access_list)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_project_ip_access_list('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_project_ip_access_list.test.id}")
        expect(ref.aws_security_group).to eq("${mongodbatlas_project_ip_access_list.test.aws_security_group}")
        expect(ref.cidr_block).to eq("${mongodbatlas_project_ip_access_list.test.cidr_block}")
        expect(ref.comment).to eq("${mongodbatlas_project_ip_access_list.test.comment}")
        expect(ref.ip_address).to eq("${mongodbatlas_project_ip_access_list.test.ip_address}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project_ip_access_list', 'test')
        expect(config).not_to have_key('aws_security_group')
        expect(config).not_to have_key('cidr_block')
        expect(config).not_to have_key('comment')
        expect(config).not_to have_key('ip_address')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ timeouts: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project_ip_access_list', 'full')
        expect(config).to have_key('timeouts')
      end
    end

    context 'optional attributes' do
      it 'includes timeouts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('opt', required_attrs.merge(timeouts: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project_ip_access_list', 'opt')
        expect(config).to have_key('timeouts')
      end

      it 'omits timeouts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project_ip_access_list', 'minimal')
        expect(config).not_to have_key('timeouts')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project_ip_access_list', 'typed')
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_ip_access_list('first', required_attrs)
        synth.mongodbatlas_project_ip_access_list('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_project_ip_access_list')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_project_ip_access_list,
    method: :mongodbatlas_project_ip_access_list,
    required_attrs: { project_id: 'test-value' },
    expected_outputs: [:id, :aws_security_group, :cidr_block, :comment, :ip_address],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
