# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_custom_dns_configuration_cluster_aws resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCustomDnsConfigurationClusterAws do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enabled: true, project_id: 'test-value' } }

  describe ':mongodbatlas_custom_dns_configuration_cluster_aws' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_dns_configuration_cluster_aws('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_custom_dns_configuration_cluster_aws', 'test')
        validate_required_attributes(config, [:enabled, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_custom_dns_configuration_cluster_aws('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_custom_dns_configuration_cluster_aws)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_custom_dns_configuration_cluster_aws('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_custom_dns_configuration_cluster_aws.test.id}")
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.mongodbatlas_custom_dns_configuration_cluster_aws("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_custom_dns_configuration_cluster_aws', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_dns_configuration_cluster_aws('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_custom_dns_configuration_cluster_aws', 'typed')
        expect([true, false]).to include(config['enabled'])
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_dns_configuration_cluster_aws('first', required_attrs)
        synth.mongodbatlas_custom_dns_configuration_cluster_aws('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_custom_dns_configuration_cluster_aws')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_custom_dns_configuration_cluster_aws,
    method: :mongodbatlas_custom_dns_configuration_cluster_aws,
    required_attrs: { enabled: true, project_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
