# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_access_list_api_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasAccessListApiKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_key_id: 'test-value', org_id: 'test-value' } }

  describe ':mongodbatlas_access_list_api_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_access_list_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_access_list_api_key', 'test')
        validate_required_attributes(config, [:api_key_id, :org_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_access_list_api_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_access_list_api_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_access_list_api_key('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_access_list_api_key.test.id}")
        expect(ref.cidr_block).to eq("${mongodbatlas_access_list_api_key.test.cidr_block}")
        expect(ref.ip_address).to eq("${mongodbatlas_access_list_api_key.test.ip_address}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_access_list_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_access_list_api_key', 'test')
        expect(config).not_to have_key('cidr_block')
        expect(config).not_to have_key('ip_address')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_access_list_api_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_access_list_api_key', 'typed')
        expect(config['api_key_id']).to be_a(String)
        expect(config['org_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_access_list_api_key('first', required_attrs)
        synth.mongodbatlas_access_list_api_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_access_list_api_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_access_list_api_key,
    method: :mongodbatlas_access_list_api_key,
    required_attrs: { api_key_id: 'test-value', org_id: 'test-value' },
    expected_outputs: [:id, :cidr_block, :ip_address],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
