# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_project resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasProject do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', org_id: 'test-value' } }

  describe ':mongodbatlas_project' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'test')
        validate_required_attributes(config, [:name, :org_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_project('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_project)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_project('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_project.test.id}")
        expect(ref.cluster_count).to eq("${mongodbatlas_project.test.cluster_count}")
        expect(ref.created).to eq("${mongodbatlas_project.test.created}")
        expect(ref.ip_addresses).to eq("${mongodbatlas_project.test.ip_addresses}")
        expect(ref.is_collect_database_specifics_statistics_enabled).to eq("${mongodbatlas_project.test.is_collect_database_specifics_statistics_enabled}")
        expect(ref.is_data_explorer_enabled).to eq("${mongodbatlas_project.test.is_data_explorer_enabled}")
        expect(ref.is_extended_storage_sizes_enabled).to eq("${mongodbatlas_project.test.is_extended_storage_sizes_enabled}")
        expect(ref.is_performance_advisor_enabled).to eq("${mongodbatlas_project.test.is_performance_advisor_enabled}")
        expect(ref.is_realtime_performance_panel_enabled).to eq("${mongodbatlas_project.test.is_realtime_performance_panel_enabled}")
        expect(ref.is_schema_advisor_enabled).to eq("${mongodbatlas_project.test.is_schema_advisor_enabled}")
        expect(ref.is_slow_operation_thresholding_enabled).to eq("${mongodbatlas_project.test.is_slow_operation_thresholding_enabled}")
        expect(ref.region_usage_restrictions).to eq("${mongodbatlas_project.test.region_usage_restrictions}")
        expect(ref.with_default_alerts_settings).to eq("${mongodbatlas_project.test.with_default_alerts_settings}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project', 'test')
        expect(config).not_to have_key('cluster_count')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('ip_addresses')
        expect(config).not_to have_key('is_collect_database_specifics_statistics_enabled')
        expect(config).not_to have_key('is_data_explorer_enabled')
        expect(config).not_to have_key('is_extended_storage_sizes_enabled')
        expect(config).not_to have_key('is_performance_advisor_enabled')
        expect(config).not_to have_key('is_realtime_performance_panel_enabled')
        expect(config).not_to have_key('is_schema_advisor_enabled')
        expect(config).not_to have_key('is_slow_operation_thresholding_enabled')
        expect(config).not_to have_key('region_usage_restrictions')
        expect(config).not_to have_key('with_default_alerts_settings')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ limits: [{ 'key1' => 'val1' }], project_owner_id: 'test-value', tags: { 'key1' => 'val1' }, teams: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project', 'full')
        expect(config).to have_key('limits')
        expect(config).to have_key('project_owner_id')
        expect(config).to have_key('tags')
        expect(config).to have_key('teams')
      end
    end

    context 'optional attributes' do
      it 'includes limits when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('opt', required_attrs.merge(limits: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'opt')
        expect(config).to have_key('limits')
      end

      it 'omits limits when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'minimal')
        expect(config).not_to have_key('limits')
      end
      it 'includes project_owner_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('opt', required_attrs.merge(project_owner_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'opt')
        expect(config).to have_key('project_owner_id')
      end

      it 'omits project_owner_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'minimal')
        expect(config).not_to have_key('project_owner_id')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes teams when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('opt', required_attrs.merge(teams: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'opt')
        expect(config).to have_key('teams')
      end

      it 'omits teams when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_project', 'minimal')
        expect(config).not_to have_key('teams')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['org_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project('first', required_attrs)
        synth.mongodbatlas_project('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_project')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_project,
    method: :mongodbatlas_project,
    required_attrs: { name: 'test-value', org_id: 'test-value' },
    expected_outputs: [:id, :cluster_count, :created, :ip_addresses, :is_collect_database_specifics_statistics_enabled, :is_data_explorer_enabled, :is_extended_storage_sizes_enabled, :is_performance_advisor_enabled, :is_realtime_performance_panel_enabled, :is_schema_advisor_enabled, :is_slow_operation_thresholding_enabled, :region_usage_restrictions, :with_default_alerts_settings],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
