# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_backup_compliance_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasBackupCompliancePolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { authorized_email: 'test-value', authorized_user_first_name: 'test-value', authorized_user_last_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_backup_compliance_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'test')
        validate_required_attributes(config, [:authorized_email, :authorized_user_first_name, :authorized_user_last_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_backup_compliance_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_backup_compliance_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_backup_compliance_policy('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_backup_compliance_policy.test.id}")
        expect(ref.restore_window_days).to eq("${mongodbatlas_backup_compliance_policy.test.restore_window_days}")
        expect(ref.state).to eq("${mongodbatlas_backup_compliance_policy.test.state}")
        expect(ref.updated_date).to eq("${mongodbatlas_backup_compliance_policy.test.updated_date}")
        expect(ref.updated_user).to eq("${mongodbatlas_backup_compliance_policy.test.updated_user}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'test')
        expect(config).not_to have_key('restore_window_days')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('updated_date')
        expect(config).not_to have_key('updated_user')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ copy_protection_enabled: true, encryption_at_rest_enabled: true, on_demand_policy_item: [{ 'key1' => 'val1' }], pit_enabled: true, policy_item_daily: [{ 'key1' => 'val1' }], policy_item_hourly: [{ 'key1' => 'val1' }], policy_item_monthly: [{ 'key1' => 'val1' }], policy_item_weekly: [{ 'key1' => 'val1' }], policy_item_yearly: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'full')
        expect(config).to have_key('copy_protection_enabled')
        expect(config).to have_key('encryption_at_rest_enabled')
        expect(config).to have_key('on_demand_policy_item')
        expect(config).to have_key('pit_enabled')
        expect(config).to have_key('policy_item_daily')
        expect(config).to have_key('policy_item_hourly')
        expect(config).to have_key('policy_item_monthly')
        expect(config).to have_key('policy_item_weekly')
        expect(config).to have_key('policy_item_yearly')
      end
    end

    context 'optional attributes' do
      it 'includes copy_protection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(copy_protection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('copy_protection_enabled')
      end

      it 'omits copy_protection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('copy_protection_enabled')
      end
      it 'includes encryption_at_rest_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(encryption_at_rest_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('encryption_at_rest_enabled')
      end

      it 'omits encryption_at_rest_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('encryption_at_rest_enabled')
      end
      it 'includes on_demand_policy_item when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(on_demand_policy_item: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('on_demand_policy_item')
      end

      it 'omits on_demand_policy_item when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('on_demand_policy_item')
      end
      it 'includes pit_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(pit_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('pit_enabled')
      end

      it 'omits pit_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('pit_enabled')
      end
      it 'includes policy_item_daily when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(policy_item_daily: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('policy_item_daily')
      end

      it 'omits policy_item_daily when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('policy_item_daily')
      end
      it 'includes policy_item_hourly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(policy_item_hourly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('policy_item_hourly')
      end

      it 'omits policy_item_hourly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('policy_item_hourly')
      end
      it 'includes policy_item_monthly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(policy_item_monthly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('policy_item_monthly')
      end

      it 'omits policy_item_monthly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('policy_item_monthly')
      end
      it 'includes policy_item_weekly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(policy_item_weekly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('policy_item_weekly')
      end

      it 'omits policy_item_weekly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('policy_item_weekly')
      end
      it 'includes policy_item_yearly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('opt', required_attrs.merge(policy_item_yearly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'opt')
        expect(config).to have_key('policy_item_yearly')
      end

      it 'omits policy_item_yearly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'minimal')
        expect(config).not_to have_key('policy_item_yearly')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts copy_protection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(copy_protection_enabled: val)
          synth.mongodbatlas_backup_compliance_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', "bool_#{val}")
          expect(config['copy_protection_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts encryption_at_rest_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(encryption_at_rest_enabled: val)
          synth.mongodbatlas_backup_compliance_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', "bool_#{val}")
          expect(config['encryption_at_rest_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts pit_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(pit_enabled: val)
          synth.mongodbatlas_backup_compliance_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', "bool_#{val}")
          expect(config['pit_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_backup_compliance_policy', 'typed')
        expect(config['authorized_email']).to be_a(String)
        expect(config['authorized_user_first_name']).to be_a(String)
        expect(config['authorized_user_last_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_backup_compliance_policy('first', required_attrs)
        synth.mongodbatlas_backup_compliance_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_backup_compliance_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_backup_compliance_policy,
    method: :mongodbatlas_backup_compliance_policy,
    required_attrs: { authorized_email: 'test-value', authorized_user_first_name: 'test-value', authorized_user_last_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :restore_window_days, :state, :updated_date, :updated_user],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:copy_protection_enabled, :encryption_at_rest_enabled, :pit_enabled]
end
