# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_search_index resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasSearchIndex do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', collection_name: 'test-value', database: 'test-value', name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_search_index' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'test')
        validate_required_attributes(config, [:cluster_name, :collection_name, :database, :name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_search_index('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_search_index)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_search_index('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_search_index.test.id}")
        expect(ref.index_id).to eq("${mongodbatlas_search_index.test.index_id}")
        expect(ref.status).to eq("${mongodbatlas_search_index.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'test')
        expect(config).not_to have_key('index_id')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ analyzer: 'test-value', analyzers: 'test-value', fields: 'test-value', mappings_dynamic: true, mappings_fields: 'test-value', search_analyzer: 'test-value', stored_source: 'test-value', synonyms: [{ 'key1' => 'val1' }], type: 'test-value', wait_for_index_build_completion: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'full')
        expect(config).to have_key('analyzer')
        expect(config).to have_key('analyzers')
        expect(config).to have_key('fields')
        expect(config).to have_key('mappings_dynamic')
        expect(config).to have_key('mappings_fields')
        expect(config).to have_key('search_analyzer')
        expect(config).to have_key('stored_source')
        expect(config).to have_key('synonyms')
        expect(config).to have_key('type')
        expect(config).to have_key('wait_for_index_build_completion')
      end
    end

    context 'optional attributes' do
      it 'includes analyzer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(analyzer: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('analyzer')
      end

      it 'omits analyzer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('analyzer')
      end
      it 'includes analyzers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(analyzers: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('analyzers')
      end

      it 'omits analyzers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('analyzers')
      end
      it 'includes fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(fields: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('fields')
      end

      it 'omits fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('fields')
      end
      it 'includes mappings_dynamic when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(mappings_dynamic: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('mappings_dynamic')
      end

      it 'omits mappings_dynamic when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('mappings_dynamic')
      end
      it 'includes mappings_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(mappings_fields: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('mappings_fields')
      end

      it 'omits mappings_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('mappings_fields')
      end
      it 'includes search_analyzer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(search_analyzer: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('search_analyzer')
      end

      it 'omits search_analyzer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('search_analyzer')
      end
      it 'includes stored_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(stored_source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('stored_source')
      end

      it 'omits stored_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('stored_source')
      end
      it 'includes synonyms when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(synonyms: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('synonyms')
      end

      it 'omits synonyms when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('synonyms')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('type')
      end
      it 'includes wait_for_index_build_completion when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('opt', required_attrs.merge(wait_for_index_build_completion: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'opt')
        expect(config).to have_key('wait_for_index_build_completion')
      end

      it 'omits wait_for_index_build_completion when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'minimal')
        expect(config).not_to have_key('wait_for_index_build_completion')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts mappings_dynamic=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(mappings_dynamic: val)
          synth.mongodbatlas_search_index("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_search_index', "bool_#{val}")
          expect(config['mappings_dynamic']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wait_for_index_build_completion=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_index_build_completion: val)
          synth.mongodbatlas_search_index("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_search_index', "bool_#{val}")
          expect(config['wait_for_index_build_completion']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_search_index', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['collection_name']).to be_a(String)
        expect(config['database']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_search_index('first', required_attrs)
        synth.mongodbatlas_search_index('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_search_index')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_search_index,
    method: :mongodbatlas_search_index,
    required_attrs: { cluster_name: 'test-value', collection_name: 'test-value', database: 'test-value', name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :index_id, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:mappings_dynamic, :wait_for_index_build_completion]
end
