# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_maintenance_window resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasMaintenanceWindow do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { day_of_week: 3.14, project_id: 'test-value' } }

  describe ':mongodbatlas_maintenance_window' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_maintenance_window', 'test')
        validate_required_attributes(config, [:day_of_week, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_maintenance_window('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_maintenance_window)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_maintenance_window('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_maintenance_window.test.id}")
        expect(ref.auto_defer).to eq("${mongodbatlas_maintenance_window.test.auto_defer}")
        expect(ref.auto_defer_once_enabled).to eq("${mongodbatlas_maintenance_window.test.auto_defer_once_enabled}")
        expect(ref.defer).to eq("${mongodbatlas_maintenance_window.test.defer}")
        expect(ref.hour_of_day).to eq("${mongodbatlas_maintenance_window.test.hour_of_day}")
        expect(ref.number_of_deferrals).to eq("${mongodbatlas_maintenance_window.test.number_of_deferrals}")
        expect(ref.start_asap).to eq("${mongodbatlas_maintenance_window.test.start_asap}")
        expect(ref.time_zone_id).to eq("${mongodbatlas_maintenance_window.test.time_zone_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_maintenance_window', 'test')
        expect(config).not_to have_key('auto_defer')
        expect(config).not_to have_key('auto_defer_once_enabled')
        expect(config).not_to have_key('defer')
        expect(config).not_to have_key('hour_of_day')
        expect(config).not_to have_key('number_of_deferrals')
        expect(config).not_to have_key('start_asap')
        expect(config).not_to have_key('time_zone_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ protected_hours: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_maintenance_window', 'full')
        expect(config).to have_key('protected_hours')
      end
    end

    context 'optional attributes' do
      it 'includes protected_hours when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('opt', required_attrs.merge(protected_hours: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_maintenance_window', 'opt')
        expect(config).to have_key('protected_hours')
      end

      it 'omits protected_hours when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_maintenance_window', 'minimal')
        expect(config).not_to have_key('protected_hours')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_maintenance_window', 'typed')
        expect(config['day_of_week']).to be_a(Float)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_maintenance_window('first', required_attrs)
        synth.mongodbatlas_maintenance_window('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_maintenance_window')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_maintenance_window,
    method: :mongodbatlas_maintenance_window,
    required_attrs: { day_of_week: 3.14, project_id: 'test-value' },
    expected_outputs: [:id, :auto_defer, :auto_defer_once_enabled, :defer, :hour_of_day, :number_of_deferrals, :start_asap, :time_zone_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
