# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_online_archive resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasOnlineArchive do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', coll_name: 'test-value', criteria: [{ 'key1' => 'val1' }], db_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_online_archive' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'test')
        validate_required_attributes(config, [:cluster_name, :coll_name, :criteria, :db_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_online_archive('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_online_archive)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_online_archive('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_online_archive.test.id}")
        expect(ref.archive_id).to eq("${mongodbatlas_online_archive.test.archive_id}")
        expect(ref.collection_type).to eq("${mongodbatlas_online_archive.test.collection_type}")
        expect(ref.paused).to eq("${mongodbatlas_online_archive.test.paused}")
        expect(ref.state).to eq("${mongodbatlas_online_archive.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'test')
        expect(config).not_to have_key('archive_id')
        expect(config).not_to have_key('collection_type')
        expect(config).not_to have_key('paused')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_expiration_rule: [{ 'key1' => 'val1' }], data_process_region: [{ 'key1' => 'val1' }], partition_fields: [{ 'key1' => 'val1' }], schedule: [{ 'key1' => 'val1' }], sync_creation: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'full')
        expect(config).to have_key('data_expiration_rule')
        expect(config).to have_key('data_process_region')
        expect(config).to have_key('partition_fields')
        expect(config).to have_key('schedule')
        expect(config).to have_key('sync_creation')
      end
    end

    context 'optional attributes' do
      it 'includes data_expiration_rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('opt', required_attrs.merge(data_expiration_rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'opt')
        expect(config).to have_key('data_expiration_rule')
      end

      it 'omits data_expiration_rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'minimal')
        expect(config).not_to have_key('data_expiration_rule')
      end
      it 'includes data_process_region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('opt', required_attrs.merge(data_process_region: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'opt')
        expect(config).to have_key('data_process_region')
      end

      it 'omits data_process_region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'minimal')
        expect(config).not_to have_key('data_process_region')
      end
      it 'includes partition_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('opt', required_attrs.merge(partition_fields: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'opt')
        expect(config).to have_key('partition_fields')
      end

      it 'omits partition_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'minimal')
        expect(config).not_to have_key('partition_fields')
      end
      it 'includes schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('opt', required_attrs.merge(schedule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'opt')
        expect(config).to have_key('schedule')
      end

      it 'omits schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'minimal')
        expect(config).not_to have_key('schedule')
      end
      it 'includes sync_creation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('opt', required_attrs.merge(sync_creation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'opt')
        expect(config).to have_key('sync_creation')
      end

      it 'omits sync_creation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'minimal')
        expect(config).not_to have_key('sync_creation')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts sync_creation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(sync_creation: val)
          synth.mongodbatlas_online_archive("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_online_archive', "bool_#{val}")
          expect(config['sync_creation']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_online_archive', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['coll_name']).to be_a(String)
        expect(config['criteria']).to be_a(Array)
        expect(config['db_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_online_archive('first', required_attrs)
        synth.mongodbatlas_online_archive('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_online_archive')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_online_archive,
    method: :mongodbatlas_online_archive,
    required_attrs: { cluster_name: 'test-value', coll_name: 'test-value', criteria: [{ 'key1' => 'val1' }], db_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :archive_id, :collection_type, :paused, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:sync_creation]
end
