# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_stream_privatelink_endpoint resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasStreamPrivatelinkEndpoint do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value', provider_name: 'test-value', vendor: 'test-value' } }

  describe ':mongodbatlas_stream_privatelink_endpoint' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'test')
        validate_required_attributes(config, [:project_id, :provider_name, :vendor])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_privatelink_endpoint('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_stream_privatelink_endpoint)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_privatelink_endpoint('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_stream_privatelink_endpoint.test.id}")
        expect(ref.error_message).to eq("${mongodbatlas_stream_privatelink_endpoint.test.error_message}")
        expect(ref.interface_endpoint_id).to eq("${mongodbatlas_stream_privatelink_endpoint.test.interface_endpoint_id}")
        expect(ref.interface_endpoint_name).to eq("${mongodbatlas_stream_privatelink_endpoint.test.interface_endpoint_name}")
        expect(ref.provider_account_id).to eq("${mongodbatlas_stream_privatelink_endpoint.test.provider_account_id}")
        expect(ref.region).to eq("${mongodbatlas_stream_privatelink_endpoint.test.region}")
        expect(ref.state).to eq("${mongodbatlas_stream_privatelink_endpoint.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'test')
        expect(config).not_to have_key('error_message')
        expect(config).not_to have_key('interface_endpoint_id')
        expect(config).not_to have_key('interface_endpoint_name')
        expect(config).not_to have_key('provider_account_id')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ arn: 'test-value', dns_domain: 'test-value', dns_sub_domain: ['test-value'], service_endpoint_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'full')
        expect(config).to have_key('arn')
        expect(config).to have_key('dns_domain')
        expect(config).to have_key('dns_sub_domain')
        expect(config).to have_key('service_endpoint_id')
      end
    end

    context 'optional attributes' do
      it 'includes arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('opt', required_attrs.merge(arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'opt')
        expect(config).to have_key('arn')
      end

      it 'omits arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'minimal')
        expect(config).not_to have_key('arn')
      end
      it 'includes dns_domain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('opt', required_attrs.merge(dns_domain: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'opt')
        expect(config).to have_key('dns_domain')
      end

      it 'omits dns_domain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'minimal')
        expect(config).not_to have_key('dns_domain')
      end
      it 'includes dns_sub_domain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('opt', required_attrs.merge(dns_sub_domain: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'opt')
        expect(config).to have_key('dns_sub_domain')
      end

      it 'omits dns_sub_domain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'minimal')
        expect(config).not_to have_key('dns_sub_domain')
      end
      it 'includes service_endpoint_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('opt', required_attrs.merge(service_endpoint_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'opt')
        expect(config).to have_key('service_endpoint_id')
      end

      it 'omits service_endpoint_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'minimal')
        expect(config).not_to have_key('service_endpoint_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_privatelink_endpoint', 'typed')
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
        expect(config['vendor']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_privatelink_endpoint('first', required_attrs)
        synth.mongodbatlas_stream_privatelink_endpoint('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_stream_privatelink_endpoint')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_stream_privatelink_endpoint,
    method: :mongodbatlas_stream_privatelink_endpoint,
    required_attrs: { project_id: 'test-value', provider_name: 'test-value', vendor: 'test-value' },
    expected_outputs: [:id, :error_message, :interface_endpoint_id, :interface_endpoint_name, :provider_account_id, :region, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
