# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_federated_database_instance resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasFederatedDatabaseInstance do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_federated_database_instance' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'test')
        validate_required_attributes(config, [:name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_database_instance('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_federated_database_instance)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_database_instance('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_federated_database_instance.test.id}")
        expect(ref.hostnames).to eq("${mongodbatlas_federated_database_instance.test.hostnames}")
        expect(ref.state).to eq("${mongodbatlas_federated_database_instance.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'test')
        expect(config).not_to have_key('hostnames')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cloud_provider_config: [{ 'key1' => 'val1' }], data_process_region: [{ 'key1' => 'val1' }], storage_databases: [{ 'key1' => 'val1' }], storage_stores: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'full')
        expect(config).to have_key('cloud_provider_config')
        expect(config).to have_key('data_process_region')
        expect(config).to have_key('storage_databases')
        expect(config).to have_key('storage_stores')
      end
    end

    context 'optional attributes' do
      it 'includes cloud_provider_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('opt', required_attrs.merge(cloud_provider_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'opt')
        expect(config).to have_key('cloud_provider_config')
      end

      it 'omits cloud_provider_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'minimal')
        expect(config).not_to have_key('cloud_provider_config')
      end
      it 'includes data_process_region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('opt', required_attrs.merge(data_process_region: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'opt')
        expect(config).to have_key('data_process_region')
      end

      it 'omits data_process_region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'minimal')
        expect(config).not_to have_key('data_process_region')
      end
      it 'includes storage_databases when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('opt', required_attrs.merge(storage_databases: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'opt')
        expect(config).to have_key('storage_databases')
      end

      it 'omits storage_databases when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'minimal')
        expect(config).not_to have_key('storage_databases')
      end
      it 'includes storage_stores when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('opt', required_attrs.merge(storage_stores: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'opt')
        expect(config).to have_key('storage_stores')
      end

      it 'omits storage_stores when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'minimal')
        expect(config).not_to have_key('storage_stores')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_database_instance', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_database_instance('first', required_attrs)
        synth.mongodbatlas_federated_database_instance('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_federated_database_instance')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_federated_database_instance,
    method: :mongodbatlas_federated_database_instance,
    required_attrs: { name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :hostnames, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
