# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cloud_provider_access_setup resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCloudProviderAccessSetup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value', provider_name: 'test-value' } }

  describe ':mongodbatlas_cloud_provider_access_setup' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_setup', 'test')
        validate_required_attributes(config, [:project_id, :provider_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_provider_access_setup('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cloud_provider_access_setup)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_provider_access_setup('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cloud_provider_access_setup.test.id}")
        expect(ref.aws_config).to eq("${mongodbatlas_cloud_provider_access_setup.test.aws_config}")
        expect(ref.created_date).to eq("${mongodbatlas_cloud_provider_access_setup.test.created_date}")
        expect(ref.gcp_config).to eq("${mongodbatlas_cloud_provider_access_setup.test.gcp_config}")
        expect(ref.last_updated_date).to eq("${mongodbatlas_cloud_provider_access_setup.test.last_updated_date}")
        expect(ref.role_id).to eq("${mongodbatlas_cloud_provider_access_setup.test.role_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_setup', 'test')
        expect(config).not_to have_key('aws_config')
        expect(config).not_to have_key('created_date')
        expect(config).not_to have_key('gcp_config')
        expect(config).not_to have_key('last_updated_date')
        expect(config).not_to have_key('role_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ azure_config: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_setup', 'full')
        expect(config).to have_key('azure_config')
      end
    end

    context 'optional attributes' do
      it 'includes azure_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('opt', required_attrs.merge(azure_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_setup', 'opt')
        expect(config).to have_key('azure_config')
      end

      it 'omits azure_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_setup', 'minimal')
        expect(config).not_to have_key('azure_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_provider_access_setup', 'typed')
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_provider_access_setup('first', required_attrs)
        synth.mongodbatlas_cloud_provider_access_setup('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cloud_provider_access_setup')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cloud_provider_access_setup,
    method: :mongodbatlas_cloud_provider_access_setup,
    required_attrs: { project_id: 'test-value', provider_name: 'test-value' },
    expected_outputs: [:id, :aws_config, :created_date, :gcp_config, :last_updated_date, :role_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
