# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cloud_backup_snapshot_export_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCloudBackupSnapshotExportJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', export_bucket_id: 'test-value', project_id: 'test-value', snapshot_id: 'test-value' } }

  describe ':mongodbatlas_cloud_backup_snapshot_export_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_export_job', 'test')
        validate_required_attributes(config, [:cluster_name, :export_bucket_id, :project_id, :snapshot_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_snapshot_export_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cloud_backup_snapshot_export_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_snapshot_export_job('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.id}")
        expect(ref.components).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.components}")
        expect(ref.created_at).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.created_at}")
        expect(ref.export_job_id).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.export_job_id}")
        expect(ref.export_status_exported_collections).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.export_status_exported_collections}")
        expect(ref.export_status_total_collections).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.export_status_total_collections}")
        expect(ref.finished_at).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.finished_at}")
        expect(ref.prefix).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.prefix}")
        expect(ref.state).to eq("${mongodbatlas_cloud_backup_snapshot_export_job.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_export_job', 'test')
        expect(config).not_to have_key('components')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('export_job_id')
        expect(config).not_to have_key('export_status_exported_collections')
        expect(config).not_to have_key('export_status_total_collections')
        expect(config).not_to have_key('finished_at')
        expect(config).not_to have_key('prefix')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_data: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_export_job', 'full')
        expect(config).to have_key('custom_data')
      end
    end

    context 'optional attributes' do
      it 'includes custom_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('opt', required_attrs.merge(custom_data: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_export_job', 'opt')
        expect(config).to have_key('custom_data')
      end

      it 'omits custom_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_export_job', 'minimal')
        expect(config).not_to have_key('custom_data')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_export_job', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['export_bucket_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['snapshot_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('first', required_attrs)
        synth.mongodbatlas_cloud_backup_snapshot_export_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cloud_backup_snapshot_export_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cloud_backup_snapshot_export_job,
    method: :mongodbatlas_cloud_backup_snapshot_export_job,
    required_attrs: { cluster_name: 'test-value', export_bucket_id: 'test-value', project_id: 'test-value', snapshot_id: 'test-value' },
    expected_outputs: [:id, :components, :created_at, :export_job_id, :export_status_exported_collections, :export_status_total_collections, :finished_at, :prefix, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
