# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cloud_backup_snapshot resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCloudBackupSnapshot do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', description: 'test-value', project_id: 'test-value', retention_in_days: 3.14 } }

  describe ':mongodbatlas_cloud_backup_snapshot' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot', 'test')
        validate_required_attributes(config, [:cluster_name, :description, :project_id, :retention_in_days])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_snapshot('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cloud_backup_snapshot)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_snapshot('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cloud_backup_snapshot.test.id}")
        expect(ref.cloud_provider).to eq("${mongodbatlas_cloud_backup_snapshot.test.cloud_provider}")
        expect(ref.created_at).to eq("${mongodbatlas_cloud_backup_snapshot.test.created_at}")
        expect(ref.expires_at).to eq("${mongodbatlas_cloud_backup_snapshot.test.expires_at}")
        expect(ref.master_key_uuid).to eq("${mongodbatlas_cloud_backup_snapshot.test.master_key_uuid}")
        expect(ref.members).to eq("${mongodbatlas_cloud_backup_snapshot.test.members}")
        expect(ref.mongod_version).to eq("${mongodbatlas_cloud_backup_snapshot.test.mongod_version}")
        expect(ref.replica_set_name).to eq("${mongodbatlas_cloud_backup_snapshot.test.replica_set_name}")
        expect(ref.snapshot_id).to eq("${mongodbatlas_cloud_backup_snapshot.test.snapshot_id}")
        expect(ref.snapshot_ids).to eq("${mongodbatlas_cloud_backup_snapshot.test.snapshot_ids}")
        expect(ref.snapshot_type).to eq("${mongodbatlas_cloud_backup_snapshot.test.snapshot_type}")
        expect(ref.status).to eq("${mongodbatlas_cloud_backup_snapshot.test.status}")
        expect(ref.storage_size_bytes).to eq("${mongodbatlas_cloud_backup_snapshot.test.storage_size_bytes}")
        expect(ref.type).to eq("${mongodbatlas_cloud_backup_snapshot.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot', 'test')
        expect(config).not_to have_key('cloud_provider')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('expires_at')
        expect(config).not_to have_key('master_key_uuid')
        expect(config).not_to have_key('members')
        expect(config).not_to have_key('mongod_version')
        expect(config).not_to have_key('replica_set_name')
        expect(config).not_to have_key('snapshot_id')
        expect(config).not_to have_key('snapshot_ids')
        expect(config).not_to have_key('snapshot_type')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('storage_size_bytes')
        expect(config).not_to have_key('type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['description']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['retention_in_days']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot('first', required_attrs)
        synth.mongodbatlas_cloud_backup_snapshot('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cloud_backup_snapshot')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cloud_backup_snapshot,
    method: :mongodbatlas_cloud_backup_snapshot,
    required_attrs: { cluster_name: 'test-value', description: 'test-value', project_id: 'test-value', retention_in_days: 3.14 },
    expected_outputs: [:id, :cloud_provider, :created_at, :expires_at, :master_key_uuid, :members, :mongod_version, :replica_set_name, :snapshot_id, :snapshot_ids, :snapshot_type, :status, :storage_size_bytes, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
