# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_privatelink_endpoint resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasPrivatelinkEndpoint do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value', provider_name: 'test-value', region: 'test-value' } }

  describe ':mongodbatlas_privatelink_endpoint' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint', 'test')
        validate_required_attributes(config, [:project_id, :provider_name, :region])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_privatelink_endpoint)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_privatelink_endpoint.test.id}")
        expect(ref.endpoint_group_names).to eq("${mongodbatlas_privatelink_endpoint.test.endpoint_group_names}")
        expect(ref.endpoint_service_name).to eq("${mongodbatlas_privatelink_endpoint.test.endpoint_service_name}")
        expect(ref.error_message).to eq("${mongodbatlas_privatelink_endpoint.test.error_message}")
        expect(ref.interface_endpoints).to eq("${mongodbatlas_privatelink_endpoint.test.interface_endpoints}")
        expect(ref.private_endpoints).to eq("${mongodbatlas_privatelink_endpoint.test.private_endpoints}")
        expect(ref.private_link_id).to eq("${mongodbatlas_privatelink_endpoint.test.private_link_id}")
        expect(ref.private_link_service_name).to eq("${mongodbatlas_privatelink_endpoint.test.private_link_service_name}")
        expect(ref.private_link_service_resource_id).to eq("${mongodbatlas_privatelink_endpoint.test.private_link_service_resource_id}")
        expect(ref.region_name).to eq("${mongodbatlas_privatelink_endpoint.test.region_name}")
        expect(ref.service_attachment_names).to eq("${mongodbatlas_privatelink_endpoint.test.service_attachment_names}")
        expect(ref.status).to eq("${mongodbatlas_privatelink_endpoint.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint', 'test')
        expect(config).not_to have_key('endpoint_group_names')
        expect(config).not_to have_key('endpoint_service_name')
        expect(config).not_to have_key('error_message')
        expect(config).not_to have_key('interface_endpoints')
        expect(config).not_to have_key('private_endpoints')
        expect(config).not_to have_key('private_link_id')
        expect(config).not_to have_key('private_link_service_name')
        expect(config).not_to have_key('private_link_service_resource_id')
        expect(config).not_to have_key('region_name')
        expect(config).not_to have_key('service_attachment_names')
        expect(config).not_to have_key('status')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint', 'typed')
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
        expect(config['region']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint('first', required_attrs)
        synth.mongodbatlas_privatelink_endpoint('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_privatelink_endpoint')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_privatelink_endpoint,
    method: :mongodbatlas_privatelink_endpoint,
    required_attrs: { project_id: 'test-value', provider_name: 'test-value', region: 'test-value' },
    expected_outputs: [:id, :endpoint_group_names, :endpoint_service_name, :error_message, :interface_endpoints, :private_endpoints, :private_link_id, :private_link_service_name, :private_link_service_resource_id, :region_name, :service_attachment_names, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
