# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_privatelink_endpoint_service_data_federation_online_archive resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasPrivatelinkEndpointServiceDataFederationOnlineArchive do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { endpoint_id: 'test-value', project_id: 'test-value', provider_name: 'test-value' } }

  describe ':mongodbatlas_privatelink_endpoint_service_data_federation_online_archive' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'test')
        validate_required_attributes(config, [:endpoint_id, :project_id, :provider_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_privatelink_endpoint_service_data_federation_online_archive)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_privatelink_endpoint_service_data_federation_online_archive.test.id}")
        expect(ref.type).to eq("${mongodbatlas_privatelink_endpoint_service_data_federation_online_archive.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'test')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', customer_endpoint_dns_name: 'test-value', region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('customer_endpoint_dns_name')
        expect(config).to have_key('region')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes customer_endpoint_dns_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('opt', required_attrs.merge(customer_endpoint_dns_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'opt')
        expect(config).to have_key('customer_endpoint_dns_name')
      end

      it 'omits customer_endpoint_dns_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'minimal')
        expect(config).not_to have_key('customer_endpoint_dns_name')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'minimal')
        expect(config).not_to have_key('region')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive', 'typed')
        expect(config['endpoint_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('first', required_attrs)
        synth.mongodbatlas_privatelink_endpoint_service_data_federation_online_archive('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_privatelink_endpoint_service_data_federation_online_archive')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_privatelink_endpoint_service_data_federation_online_archive,
    method: :mongodbatlas_privatelink_endpoint_service_data_federation_online_archive,
    required_attrs: { endpoint_id: 'test-value', project_id: 'test-value', provider_name: 'test-value' },
    expected_outputs: [:id, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
