# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_project_api_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasProjectApiKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', project_assignment: [{ 'key1' => 'val1' }] } }

  describe ':mongodbatlas_project_api_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_project_api_key', 'test')
        validate_required_attributes(config, [:description, :project_assignment])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_project_api_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_project_api_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_project_api_key('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_project_api_key.test.id}")
        expect(ref.api_key_id).to eq("${mongodbatlas_project_api_key.test.api_key_id}")
        expect(ref.private_key).to eq("${mongodbatlas_project_api_key.test.private_key}")
        expect(ref.public_key).to eq("${mongodbatlas_project_api_key.test.public_key}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project_api_key', 'test')
        expect(config).not_to have_key('api_key_id')
        expect(config).not_to have_key('private_key')
        expect(config).not_to have_key('public_key')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key]
        expect(sensitive_fields).to include(:private_key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_api_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_project_api_key', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['project_assignment']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_project_api_key('first', required_attrs)
        synth.mongodbatlas_project_api_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_project_api_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_project_api_key,
    method: :mongodbatlas_project_api_key,
    required_attrs: { description: 'test-value', project_assignment: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :api_key_id, :private_key, :public_key],
    sensitive_fields: [:private_key],
    immutable_fields: [],
    boolean_fields: []
end
