# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_stream_connection resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasStreamConnection do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { connection_name: 'test-value', instance_name: 'test-value', project_id: 'test-value', type: 'test-value' } }

  describe ':mongodbatlas_stream_connection' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'test')
        validate_required_attributes(config, [:connection_name, :instance_name, :project_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_connection('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_stream_connection)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_connection('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_stream_connection.test.id}")
        expect(ref.networking).to eq("${mongodbatlas_stream_connection.test.networking}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'test')
        expect(config).not_to have_key('networking')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ authentication: { 'key1' => 'val1' }, aws: { 'key1' => 'val1' }, bootstrap_servers: 'test-value', cluster_name: 'test-value', cluster_project_id: 'test-value', config: { 'key1' => 'val1' }, db_role_to_execute: { 'key1' => 'val1' }, headers: { 'key1' => 'val1' }, security: { 'key1' => 'val1' }, url: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'full')
        expect(config).to have_key('authentication')
        expect(config).to have_key('aws')
        expect(config).to have_key('bootstrap_servers')
        expect(config).to have_key('cluster_name')
        expect(config).to have_key('cluster_project_id')
        expect(config).to have_key('config')
        expect(config).to have_key('db_role_to_execute')
        expect(config).to have_key('headers')
        expect(config).to have_key('security')
        expect(config).to have_key('url')
      end
    end

    context 'optional attributes' do
      it 'includes authentication when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(authentication: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('authentication')
      end

      it 'omits authentication when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('authentication')
      end
      it 'includes aws when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(aws: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('aws')
      end

      it 'omits aws when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('aws')
      end
      it 'includes bootstrap_servers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(bootstrap_servers: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('bootstrap_servers')
      end

      it 'omits bootstrap_servers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('bootstrap_servers')
      end
      it 'includes cluster_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(cluster_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('cluster_name')
      end

      it 'omits cluster_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('cluster_name')
      end
      it 'includes cluster_project_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(cluster_project_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('cluster_project_id')
      end

      it 'omits cluster_project_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('cluster_project_id')
      end
      it 'includes config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('config')
      end

      it 'omits config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('config')
      end
      it 'includes db_role_to_execute when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(db_role_to_execute: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('db_role_to_execute')
      end

      it 'omits db_role_to_execute when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('db_role_to_execute')
      end
      it 'includes headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(headers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('headers')
      end

      it 'omits headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('headers')
      end
      it 'includes security when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(security: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('security')
      end

      it 'omits security when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('security')
      end
      it 'includes url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('opt', required_attrs.merge(url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'opt')
        expect(config).to have_key('url')
      end

      it 'omits url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'minimal')
        expect(config).not_to have_key('url')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_connection', 'typed')
        expect(config['connection_name']).to be_a(String)
        expect(config['instance_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_connection('first', required_attrs)
        synth.mongodbatlas_stream_connection('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_stream_connection')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_stream_connection,
    method: :mongodbatlas_stream_connection,
    required_attrs: { connection_name: 'test-value', instance_name: 'test-value', project_id: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :networking],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
