# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_federated_query_limit resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasFederatedQueryLimit do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { limit_name: 'test-value', overrun_policy: 'test-value', project_id: 'test-value', tenant_name: 'test-value', value: 3.14 } }

  describe ':mongodbatlas_federated_query_limit' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'test')
        validate_required_attributes(config, [:limit_name, :overrun_policy, :project_id, :tenant_name, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_query_limit('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_federated_query_limit)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_query_limit('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_federated_query_limit.test.id}")
        expect(ref.current_usage).to eq("${mongodbatlas_federated_query_limit.test.current_usage}")
        expect(ref.last_modified_date).to eq("${mongodbatlas_federated_query_limit.test.last_modified_date}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'test')
        expect(config).not_to have_key('current_usage')
        expect(config).not_to have_key('last_modified_date')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ default_limit: 3.14, maximum_limit: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'full')
        expect(config).to have_key('default_limit')
        expect(config).to have_key('maximum_limit')
      end
    end

    context 'optional attributes' do
      it 'includes default_limit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('opt', required_attrs.merge(default_limit: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'opt')
        expect(config).to have_key('default_limit')
      end

      it 'omits default_limit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'minimal')
        expect(config).not_to have_key('default_limit')
      end
      it 'includes maximum_limit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('opt', required_attrs.merge(maximum_limit: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'opt')
        expect(config).to have_key('maximum_limit')
      end

      it 'omits maximum_limit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'minimal')
        expect(config).not_to have_key('maximum_limit')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_query_limit', 'typed')
        expect(config['limit_name']).to be_a(String)
        expect(config['overrun_policy']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['tenant_name']).to be_a(String)
        expect(config['value']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_query_limit('first', required_attrs)
        synth.mongodbatlas_federated_query_limit('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_federated_query_limit')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_federated_query_limit,
    method: :mongodbatlas_federated_query_limit,
    required_attrs: { limit_name: 'test-value', overrun_policy: 'test-value', project_id: 'test-value', tenant_name: 'test-value', value: 3.14 },
    expected_outputs: [:id, :current_usage, :last_modified_date],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
