# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_auditing resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasAuditing do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value' } }

  describe ':mongodbatlas_auditing' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_auditing('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_auditing', 'test')
        validate_required_attributes(config, [:project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_auditing('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_auditing)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_auditing('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_auditing.test.id}")
        expect(ref.audit_authorization_success).to eq("${mongodbatlas_auditing.test.audit_authorization_success}")
        expect(ref.audit_filter).to eq("${mongodbatlas_auditing.test.audit_filter}")
        expect(ref.configuration_type).to eq("${mongodbatlas_auditing.test.configuration_type}")
        expect(ref.enabled).to eq("${mongodbatlas_auditing.test.enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_auditing('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_auditing', 'test')
        expect(config).not_to have_key('audit_authorization_success')
        expect(config).not_to have_key('audit_filter')
        expect(config).not_to have_key('configuration_type')
        expect(config).not_to have_key('enabled')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_auditing('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_auditing', 'typed')
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_auditing('first', required_attrs)
        synth.mongodbatlas_auditing('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_auditing')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_auditing,
    method: :mongodbatlas_auditing,
    required_attrs: { project_id: 'test-value' },
    expected_outputs: [:id, :audit_authorization_success, :audit_filter, :configuration_type, :enabled],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
