# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cloud_backup_schedule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCloudBackupSchedule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_cloud_backup_schedule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'test')
        validate_required_attributes(config, [:cluster_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_schedule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cloud_backup_schedule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_schedule('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cloud_backup_schedule.test.id}")
        expect(ref.auto_export_enabled).to eq("${mongodbatlas_cloud_backup_schedule.test.auto_export_enabled}")
        expect(ref.cluster_id).to eq("${mongodbatlas_cloud_backup_schedule.test.cluster_id}")
        expect(ref.id_policy).to eq("${mongodbatlas_cloud_backup_schedule.test.id_policy}")
        expect(ref.next_snapshot).to eq("${mongodbatlas_cloud_backup_schedule.test.next_snapshot}")
        expect(ref.reference_hour_of_day).to eq("${mongodbatlas_cloud_backup_schedule.test.reference_hour_of_day}")
        expect(ref.reference_minute_of_hour).to eq("${mongodbatlas_cloud_backup_schedule.test.reference_minute_of_hour}")
        expect(ref.restore_window_days).to eq("${mongodbatlas_cloud_backup_schedule.test.restore_window_days}")
        expect(ref.update_snapshots).to eq("${mongodbatlas_cloud_backup_schedule.test.update_snapshots}")
        expect(ref.use_org_and_group_names_in_export_prefix).to eq("${mongodbatlas_cloud_backup_schedule.test.use_org_and_group_names_in_export_prefix}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'test')
        expect(config).not_to have_key('auto_export_enabled')
        expect(config).not_to have_key('cluster_id')
        expect(config).not_to have_key('id_policy')
        expect(config).not_to have_key('next_snapshot')
        expect(config).not_to have_key('reference_hour_of_day')
        expect(config).not_to have_key('reference_minute_of_hour')
        expect(config).not_to have_key('restore_window_days')
        expect(config).not_to have_key('update_snapshots')
        expect(config).not_to have_key('use_org_and_group_names_in_export_prefix')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ copy_settings: [{ 'key1' => 'val1' }], export: [{ 'key1' => 'val1' }], policy_item_daily: [{ 'key1' => 'val1' }], policy_item_hourly: [{ 'key1' => 'val1' }], policy_item_monthly: [{ 'key1' => 'val1' }], policy_item_weekly: [{ 'key1' => 'val1' }], policy_item_yearly: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'full')
        expect(config).to have_key('copy_settings')
        expect(config).to have_key('export')
        expect(config).to have_key('policy_item_daily')
        expect(config).to have_key('policy_item_hourly')
        expect(config).to have_key('policy_item_monthly')
        expect(config).to have_key('policy_item_weekly')
        expect(config).to have_key('policy_item_yearly')
      end
    end

    context 'optional attributes' do
      it 'includes copy_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(copy_settings: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('copy_settings')
      end

      it 'omits copy_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('copy_settings')
      end
      it 'includes export when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(export: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('export')
      end

      it 'omits export when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('export')
      end
      it 'includes policy_item_daily when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(policy_item_daily: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('policy_item_daily')
      end

      it 'omits policy_item_daily when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('policy_item_daily')
      end
      it 'includes policy_item_hourly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(policy_item_hourly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('policy_item_hourly')
      end

      it 'omits policy_item_hourly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('policy_item_hourly')
      end
      it 'includes policy_item_monthly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(policy_item_monthly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('policy_item_monthly')
      end

      it 'omits policy_item_monthly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('policy_item_monthly')
      end
      it 'includes policy_item_weekly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(policy_item_weekly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('policy_item_weekly')
      end

      it 'omits policy_item_weekly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('policy_item_weekly')
      end
      it 'includes policy_item_yearly when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('opt', required_attrs.merge(policy_item_yearly: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'opt')
        expect(config).to have_key('policy_item_yearly')
      end

      it 'omits policy_item_yearly when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'minimal')
        expect(config).not_to have_key('policy_item_yearly')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_schedule', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_schedule('first', required_attrs)
        synth.mongodbatlas_cloud_backup_schedule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cloud_backup_schedule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cloud_backup_schedule,
    method: :mongodbatlas_cloud_backup_schedule,
    required_attrs: { cluster_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :auto_export_enabled, :cluster_id, :id_policy, :next_snapshot, :reference_hour_of_day, :reference_minute_of_hour, :restore_window_days, :update_snapshots, :use_org_and_group_names_in_export_prefix],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
