# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_flex_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasFlexCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project_id: 'test-value', provider_settings: { 'key1' => 'val1' } } }

  describe ':mongodbatlas_flex_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_flex_cluster', 'test')
        validate_required_attributes(config, [:name, :project_id, :provider_settings])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_flex_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_flex_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_flex_cluster('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_flex_cluster.test.id}")
        expect(ref.backup_settings).to eq("${mongodbatlas_flex_cluster.test.backup_settings}")
        expect(ref.cluster_type).to eq("${mongodbatlas_flex_cluster.test.cluster_type}")
        expect(ref.connection_strings).to eq("${mongodbatlas_flex_cluster.test.connection_strings}")
        expect(ref.create_date).to eq("${mongodbatlas_flex_cluster.test.create_date}")
        expect(ref.mongo_db_version).to eq("${mongodbatlas_flex_cluster.test.mongo_db_version}")
        expect(ref.state_name).to eq("${mongodbatlas_flex_cluster.test.state_name}")
        expect(ref.termination_protection_enabled).to eq("${mongodbatlas_flex_cluster.test.termination_protection_enabled}")
        expect(ref.version_release_system).to eq("${mongodbatlas_flex_cluster.test.version_release_system}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_flex_cluster', 'test')
        expect(config).not_to have_key('backup_settings')
        expect(config).not_to have_key('cluster_type')
        expect(config).not_to have_key('connection_strings')
        expect(config).not_to have_key('create_date')
        expect(config).not_to have_key('mongo_db_version')
        expect(config).not_to have_key('state_name')
        expect(config).not_to have_key('termination_protection_enabled')
        expect(config).not_to have_key('version_release_system')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_flex_cluster', 'full')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_flex_cluster', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_flex_cluster', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_flex_cluster', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_settings']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_flex_cluster('first', required_attrs)
        synth.mongodbatlas_flex_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_flex_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_flex_cluster,
    method: :mongodbatlas_flex_cluster,
    required_attrs: { name: 'test-value', project_id: 'test-value', provider_settings: { 'key1' => 'val1' } },
    expected_outputs: [:id, :backup_settings, :cluster_type, :connection_strings, :create_date, :mongo_db_version, :state_name, :termination_protection_enabled, :version_release_system],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
