# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_custom_db_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCustomDbRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value', role_name: 'test-value' } }

  describe ':mongodbatlas_custom_db_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'test')
        validate_required_attributes(config, [:project_id, :role_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_custom_db_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_custom_db_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_custom_db_role('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_custom_db_role.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ actions: [{ 'key1' => 'val1' }], inherited_roles: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'full')
        expect(config).to have_key('actions')
        expect(config).to have_key('inherited_roles')
      end
    end

    context 'optional attributes' do
      it 'includes actions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('opt', required_attrs.merge(actions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'opt')
        expect(config).to have_key('actions')
      end

      it 'omits actions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'minimal')
        expect(config).not_to have_key('actions')
      end
      it 'includes inherited_roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('opt', required_attrs.merge(inherited_roles: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'opt')
        expect(config).to have_key('inherited_roles')
      end

      it 'omits inherited_roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'minimal')
        expect(config).not_to have_key('inherited_roles')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_custom_db_role', 'typed')
        expect(config['project_id']).to be_a(String)
        expect(config['role_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_custom_db_role('first', required_attrs)
        synth.mongodbatlas_custom_db_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_custom_db_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_custom_db_role,
    method: :mongodbatlas_custom_db_role,
    required_attrs: { project_id: 'test-value', role_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
