# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_privatelink_endpoint_service_serverless resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasPrivatelinkEndpointServiceServerless do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { endpoint_id: 'test-value', instance_name: 'test-value', project_id: 'test-value', provider_name: 'test-value' } }

  describe ':mongodbatlas_privatelink_endpoint_service_serverless' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_serverless', 'test')
        validate_required_attributes(config, [:endpoint_id, :instance_name, :project_id, :provider_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint_service_serverless('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_privatelink_endpoint_service_serverless)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint_service_serverless('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_privatelink_endpoint_service_serverless.test.id}")
        expect(ref.cloud_provider_endpoint_id).to eq("${mongodbatlas_privatelink_endpoint_service_serverless.test.cloud_provider_endpoint_id}")
        expect(ref.private_endpoint_ip_address).to eq("${mongodbatlas_privatelink_endpoint_service_serverless.test.private_endpoint_ip_address}")
        expect(ref.private_link_service_resource_id).to eq("${mongodbatlas_privatelink_endpoint_service_serverless.test.private_link_service_resource_id}")
        expect(ref.status).to eq("${mongodbatlas_privatelink_endpoint_service_serverless.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_serverless', 'test')
        expect(config).not_to have_key('cloud_provider_endpoint_id')
        expect(config).not_to have_key('private_endpoint_ip_address')
        expect(config).not_to have_key('private_link_service_resource_id')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_serverless', 'full')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_serverless', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_serverless', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service_serverless', 'typed')
        expect(config['endpoint_id']).to be_a(String)
        expect(config['instance_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('first', required_attrs)
        synth.mongodbatlas_privatelink_endpoint_service_serverless('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_privatelink_endpoint_service_serverless')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_privatelink_endpoint_service_serverless,
    method: :mongodbatlas_privatelink_endpoint_service_serverless,
    required_attrs: { endpoint_id: 'test-value', instance_name: 'test-value', project_id: 'test-value', provider_name: 'test-value' },
    expected_outputs: [:id, :cloud_provider_endpoint_id, :private_endpoint_ip_address, :private_link_service_resource_id, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
