# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cloud_backup_snapshot_restore_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCloudBackupSnapshotRestoreJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_cloud_backup_snapshot_restore_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'test')
        validate_required_attributes(config, [:cluster_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_snapshot_restore_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cloud_backup_snapshot_restore_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cloud_backup_snapshot_restore_job('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.id}")
        expect(ref.cancelled).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.cancelled}")
        expect(ref.delivery_url).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.delivery_url}")
        expect(ref.expired).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.expired}")
        expect(ref.expires_at).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.expires_at}")
        expect(ref.failed).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.failed}")
        expect(ref.finished_at).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.finished_at}")
        expect(ref.snapshot_restore_job_id).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.snapshot_restore_job_id}")
        expect(ref.timestamp).to eq("${mongodbatlas_cloud_backup_snapshot_restore_job.test.timestamp}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'test')
        expect(config).not_to have_key('cancelled')
        expect(config).not_to have_key('delivery_url')
        expect(config).not_to have_key('expired')
        expect(config).not_to have_key('expires_at')
        expect(config).not_to have_key('failed')
        expect(config).not_to have_key('finished_at')
        expect(config).not_to have_key('snapshot_restore_job_id')
        expect(config).not_to have_key('timestamp')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ delivery_type_config: [{ 'key1' => 'val1' }], snapshot_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'full')
        expect(config).to have_key('delivery_type_config')
        expect(config).to have_key('snapshot_id')
      end
    end

    context 'optional attributes' do
      it 'includes delivery_type_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('opt', required_attrs.merge(delivery_type_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'opt')
        expect(config).to have_key('delivery_type_config')
      end

      it 'omits delivery_type_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'minimal')
        expect(config).not_to have_key('delivery_type_config')
      end
      it 'includes snapshot_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('opt', required_attrs.merge(snapshot_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'opt')
        expect(config).to have_key('snapshot_id')
      end

      it 'omits snapshot_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'minimal')
        expect(config).not_to have_key('snapshot_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cloud_backup_snapshot_restore_job', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('first', required_attrs)
        synth.mongodbatlas_cloud_backup_snapshot_restore_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cloud_backup_snapshot_restore_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cloud_backup_snapshot_restore_job,
    method: :mongodbatlas_cloud_backup_snapshot_restore_job,
    required_attrs: { cluster_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :cancelled, :delivery_url, :expired, :expires_at, :failed, :finished_at, :snapshot_restore_job_id, :timestamp],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
