# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_stream_instance resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasStreamInstance do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { data_process_region: { 'key1' => 'val1' }, instance_name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_stream_instance' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_stream_instance', 'test')
        validate_required_attributes(config, [:data_process_region, :instance_name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_instance('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_stream_instance)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_stream_instance('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_stream_instance.test.id}")
        expect(ref.hostnames).to eq("${mongodbatlas_stream_instance.test.hostnames}")
        expect(ref.stream_config).to eq("${mongodbatlas_stream_instance.test.stream_config}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_instance('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_instance', 'test')
        expect(config).not_to have_key('hostnames')
        expect(config).not_to have_key('stream_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_instance('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_stream_instance', 'typed')
        expect(config['data_process_region']).to be_a(Hash)
        expect(config['instance_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_stream_instance('first', required_attrs)
        synth.mongodbatlas_stream_instance('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_stream_instance')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_stream_instance,
    method: :mongodbatlas_stream_instance,
    required_attrs: { data_process_region: { 'key1' => 'val1' }, instance_name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :hostnames, :stream_config],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
