# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_organization resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasOrganization do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':mongodbatlas_organization' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_organization('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_organization)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_organization('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_organization.test.id}")
        expect(ref.api_access_list_required).to eq("${mongodbatlas_organization.test.api_access_list_required}")
        expect(ref.multi_factor_auth_required).to eq("${mongodbatlas_organization.test.multi_factor_auth_required}")
        expect(ref.org_id).to eq("${mongodbatlas_organization.test.org_id}")
        expect(ref.private_key).to eq("${mongodbatlas_organization.test.private_key}")
        expect(ref.public_key).to eq("${mongodbatlas_organization.test.public_key}")
        expect(ref.restrict_employee_access).to eq("${mongodbatlas_organization.test.restrict_employee_access}")
        expect(ref.skip_default_alerts_settings).to eq("${mongodbatlas_organization.test.skip_default_alerts_settings}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_organization', 'test')
        expect(config).not_to have_key('api_access_list_required')
        expect(config).not_to have_key('multi_factor_auth_required')
        expect(config).not_to have_key('org_id')
        expect(config).not_to have_key('private_key')
        expect(config).not_to have_key('public_key')
        expect(config).not_to have_key('restrict_employee_access')
        expect(config).not_to have_key('skip_default_alerts_settings')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', federation_settings_id: 'test-value', gen_ai_features_enabled: true, org_owner_id: 'test-value', role_names: ['test-value'], security_contact: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_organization', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('federation_settings_id')
        expect(config).to have_key('gen_ai_features_enabled')
        expect(config).to have_key('org_owner_id')
        expect(config).to have_key('role_names')
        expect(config).to have_key('security_contact')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes federation_settings_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('opt', required_attrs.merge(federation_settings_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'opt')
        expect(config).to have_key('federation_settings_id')
      end

      it 'omits federation_settings_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'minimal')
        expect(config).not_to have_key('federation_settings_id')
      end
      it 'includes gen_ai_features_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('opt', required_attrs.merge(gen_ai_features_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'opt')
        expect(config).to have_key('gen_ai_features_enabled')
      end

      it 'omits gen_ai_features_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'minimal')
        expect(config).not_to have_key('gen_ai_features_enabled')
      end
      it 'includes org_owner_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('opt', required_attrs.merge(org_owner_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'opt')
        expect(config).to have_key('org_owner_id')
      end

      it 'omits org_owner_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'minimal')
        expect(config).not_to have_key('org_owner_id')
      end
      it 'includes role_names when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('opt', required_attrs.merge(role_names: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'opt')
        expect(config).to have_key('role_names')
      end

      it 'omits role_names when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'minimal')
        expect(config).not_to have_key('role_names')
      end
      it 'includes security_contact when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('opt', required_attrs.merge(security_contact: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'opt')
        expect(config).to have_key('security_contact')
      end

      it 'omits security_contact when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_organization', 'minimal')
        expect(config).not_to have_key('security_contact')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key, :public_key]
        expect(sensitive_fields).to include(:private_key)
        expect(sensitive_fields).to include(:public_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts gen_ai_features_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(gen_ai_features_enabled: val)
          synth.mongodbatlas_organization("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_organization', "bool_#{val}")
          expect(config['gen_ai_features_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_organization', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_organization('first', required_attrs)
        synth.mongodbatlas_organization('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_organization')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_organization,
    method: :mongodbatlas_organization,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :api_access_list_required, :multi_factor_auth_required, :org_id, :private_key, :public_key, :restrict_employee_access, :skip_default_alerts_settings],
    sensitive_fields: [:private_key, :public_key],
    immutable_fields: [],
    boolean_fields: [:gen_ai_features_enabled]
end
