# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_data_lake_pipeline resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasDataLakePipeline do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_data_lake_pipeline' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'test')
        validate_required_attributes(config, [:name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_data_lake_pipeline('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_data_lake_pipeline)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_data_lake_pipeline('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_data_lake_pipeline.test.id}")
        expect(ref.created_date).to eq("${mongodbatlas_data_lake_pipeline.test.created_date}")
        expect(ref.ingestion_schedules).to eq("${mongodbatlas_data_lake_pipeline.test.ingestion_schedules}")
        expect(ref.last_updated_date).to eq("${mongodbatlas_data_lake_pipeline.test.last_updated_date}")
        expect(ref.snapshots).to eq("${mongodbatlas_data_lake_pipeline.test.snapshots}")
        expect(ref.state).to eq("${mongodbatlas_data_lake_pipeline.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'test')
        expect(config).not_to have_key('created_date')
        expect(config).not_to have_key('ingestion_schedules')
        expect(config).not_to have_key('last_updated_date')
        expect(config).not_to have_key('snapshots')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ sink: [{ 'key1' => 'val1' }], source: [{ 'key1' => 'val1' }], transformations: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'full')
        expect(config).to have_key('sink')
        expect(config).to have_key('source')
        expect(config).to have_key('transformations')
      end
    end

    context 'optional attributes' do
      it 'includes sink when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('opt', required_attrs.merge(sink: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'opt')
        expect(config).to have_key('sink')
      end

      it 'omits sink when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'minimal')
        expect(config).not_to have_key('sink')
      end
      it 'includes source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('opt', required_attrs.merge(source: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'opt')
        expect(config).to have_key('source')
      end

      it 'omits source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'minimal')
        expect(config).not_to have_key('source')
      end
      it 'includes transformations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('opt', required_attrs.merge(transformations: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'opt')
        expect(config).to have_key('transformations')
      end

      it 'omits transformations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'minimal')
        expect(config).not_to have_key('transformations')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_data_lake_pipeline', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_data_lake_pipeline('first', required_attrs)
        synth.mongodbatlas_data_lake_pipeline('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_data_lake_pipeline')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_data_lake_pipeline,
    method: :mongodbatlas_data_lake_pipeline,
    required_attrs: { name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :created_date, :ingestion_schedules, :last_updated_date, :snapshots, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
