# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cluster_outage_simulation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasClusterOutageSimulation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_name: 'test-value', outage_filters: [{ 'key1' => 'val1' }], project_id: 'test-value' } }

  describe ':mongodbatlas_cluster_outage_simulation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster_outage_simulation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cluster_outage_simulation', 'test')
        validate_required_attributes(config, [:cluster_name, :outage_filters, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cluster_outage_simulation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cluster_outage_simulation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cluster_outage_simulation('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cluster_outage_simulation.test.id}")
        expect(ref.simulation_id).to eq("${mongodbatlas_cluster_outage_simulation.test.simulation_id}")
        expect(ref.start_request_date).to eq("${mongodbatlas_cluster_outage_simulation.test.start_request_date}")
        expect(ref.state).to eq("${mongodbatlas_cluster_outage_simulation.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster_outage_simulation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cluster_outage_simulation', 'test')
        expect(config).not_to have_key('simulation_id')
        expect(config).not_to have_key('start_request_date')
        expect(config).not_to have_key('state')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster_outage_simulation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cluster_outage_simulation', 'typed')
        expect(config['cluster_name']).to be_a(String)
        expect(config['outage_filters']).to be_a(Array)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster_outage_simulation('first', required_attrs)
        synth.mongodbatlas_cluster_outage_simulation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cluster_outage_simulation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cluster_outage_simulation,
    method: :mongodbatlas_cluster_outage_simulation,
    required_attrs: { cluster_name: 'test-value', outage_filters: [{ 'key1' => 'val1' }], project_id: 'test-value' },
    expected_outputs: [:id, :simulation_id, :start_request_date, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
