# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_privatelink_endpoint_service resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasPrivatelinkEndpointService do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { endpoint_service_id: 'test-value', private_link_id: 'test-value', project_id: 'test-value', provider_name: 'test-value' } }

  describe ':mongodbatlas_privatelink_endpoint_service' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'test')
        validate_required_attributes(config, [:endpoint_service_id, :private_link_id, :project_id, :provider_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint_service('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_privatelink_endpoint_service)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_privatelink_endpoint_service('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_privatelink_endpoint_service.test.id}")
        expect(ref.aws_connection_status).to eq("${mongodbatlas_privatelink_endpoint_service.test.aws_connection_status}")
        expect(ref.azure_status).to eq("${mongodbatlas_privatelink_endpoint_service.test.azure_status}")
        expect(ref.delete_requested).to eq("${mongodbatlas_privatelink_endpoint_service.test.delete_requested}")
        expect(ref.endpoint_group_name).to eq("${mongodbatlas_privatelink_endpoint_service.test.endpoint_group_name}")
        expect(ref.error_message).to eq("${mongodbatlas_privatelink_endpoint_service.test.error_message}")
        expect(ref.gcp_status).to eq("${mongodbatlas_privatelink_endpoint_service.test.gcp_status}")
        expect(ref.interface_endpoint_id).to eq("${mongodbatlas_privatelink_endpoint_service.test.interface_endpoint_id}")
        expect(ref.private_endpoint_connection_name).to eq("${mongodbatlas_privatelink_endpoint_service.test.private_endpoint_connection_name}")
        expect(ref.private_endpoint_ip_address).to eq("${mongodbatlas_privatelink_endpoint_service.test.private_endpoint_ip_address}")
        expect(ref.private_endpoint_resource_id).to eq("${mongodbatlas_privatelink_endpoint_service.test.private_endpoint_resource_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'test')
        expect(config).not_to have_key('aws_connection_status')
        expect(config).not_to have_key('azure_status')
        expect(config).not_to have_key('delete_requested')
        expect(config).not_to have_key('endpoint_group_name')
        expect(config).not_to have_key('error_message')
        expect(config).not_to have_key('gcp_status')
        expect(config).not_to have_key('interface_endpoint_id')
        expect(config).not_to have_key('private_endpoint_connection_name')
        expect(config).not_to have_key('private_endpoint_ip_address')
        expect(config).not_to have_key('private_endpoint_resource_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ endpoints: [{ 'key1' => 'val1' }], gcp_project_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'full')
        expect(config).to have_key('endpoints')
        expect(config).to have_key('gcp_project_id')
      end
    end

    context 'optional attributes' do
      it 'includes endpoints when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('opt', required_attrs.merge(endpoints: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'opt')
        expect(config).to have_key('endpoints')
      end

      it 'omits endpoints when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'minimal')
        expect(config).not_to have_key('endpoints')
      end
      it 'includes gcp_project_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('opt', required_attrs.merge(gcp_project_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'opt')
        expect(config).to have_key('gcp_project_id')
      end

      it 'omits gcp_project_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'minimal')
        expect(config).not_to have_key('gcp_project_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_privatelink_endpoint_service', 'typed')
        expect(config['endpoint_service_id']).to be_a(String)
        expect(config['private_link_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_privatelink_endpoint_service('first', required_attrs)
        synth.mongodbatlas_privatelink_endpoint_service('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_privatelink_endpoint_service')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_privatelink_endpoint_service,
    method: :mongodbatlas_privatelink_endpoint_service,
    required_attrs: { endpoint_service_id: 'test-value', private_link_id: 'test-value', project_id: 'test-value', provider_name: 'test-value' },
    expected_outputs: [:id, :aws_connection_status, :azure_status, :delete_requested, :endpoint_group_name, :error_message, :gcp_status, :interface_endpoint_id, :private_endpoint_connection_name, :private_endpoint_ip_address, :private_endpoint_resource_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
