# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_org_invitation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasOrgInvitation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { org_id: 'test-value', roles: ['test-value'], username: 'test-value' } }

  describe ':mongodbatlas_org_invitation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_org_invitation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_org_invitation', 'test')
        validate_required_attributes(config, [:org_id, :roles, :username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_org_invitation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_org_invitation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_org_invitation('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_org_invitation.test.id}")
        expect(ref.created_at).to eq("${mongodbatlas_org_invitation.test.created_at}")
        expect(ref.expires_at).to eq("${mongodbatlas_org_invitation.test.expires_at}")
        expect(ref.invitation_id).to eq("${mongodbatlas_org_invitation.test.invitation_id}")
        expect(ref.inviter_username).to eq("${mongodbatlas_org_invitation.test.inviter_username}")
        expect(ref.teams_ids).to eq("${mongodbatlas_org_invitation.test.teams_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_org_invitation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_org_invitation', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('expires_at')
        expect(config).not_to have_key('invitation_id')
        expect(config).not_to have_key('inviter_username')
        expect(config).not_to have_key('teams_ids')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_org_invitation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_org_invitation', 'typed')
        expect(config['org_id']).to be_a(String)
        expect(config['roles']).to be_a(Array)
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_org_invitation('first', required_attrs)
        synth.mongodbatlas_org_invitation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_org_invitation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_org_invitation,
    method: :mongodbatlas_org_invitation,
    required_attrs: { org_id: 'test-value', roles: ['test-value'], username: 'test-value' },
    expected_outputs: [:id, :created_at, :expires_at, :invitation_id, :inviter_username, :teams_ids],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
