# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project_id: 'test-value', provider_instance_size_name: 'test-value', provider_name: 'test-value' } }

  describe ':mongodbatlas_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'test')
        validate_required_attributes(config, [:name, :project_id, :provider_instance_size_name, :provider_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_cluster('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_cluster.test.id}")
        expect(ref.accept_data_risks_and_force_replica_set_reconfig).to eq("${mongodbatlas_cluster.test.accept_data_risks_and_force_replica_set_reconfig}")
        expect(ref.auto_scaling_compute_enabled).to eq("${mongodbatlas_cluster.test.auto_scaling_compute_enabled}")
        expect(ref.auto_scaling_compute_scale_down_enabled).to eq("${mongodbatlas_cluster.test.auto_scaling_compute_scale_down_enabled}")
        expect(ref.auto_scaling_disk_gb_enabled).to eq("${mongodbatlas_cluster.test.auto_scaling_disk_gb_enabled}")
        expect(ref.backing_provider_name).to eq("${mongodbatlas_cluster.test.backing_provider_name}")
        expect(ref.backup_enabled).to eq("${mongodbatlas_cluster.test.backup_enabled}")
        expect(ref.cloud_backup).to eq("${mongodbatlas_cluster.test.cloud_backup}")
        expect(ref.cluster_id).to eq("${mongodbatlas_cluster.test.cluster_id}")
        expect(ref.cluster_type).to eq("${mongodbatlas_cluster.test.cluster_type}")
        expect(ref.connection_strings).to eq("${mongodbatlas_cluster.test.connection_strings}")
        expect(ref.container_id).to eq("${mongodbatlas_cluster.test.container_id}")
        expect(ref.disk_size_gb).to eq("${mongodbatlas_cluster.test.disk_size_gb}")
        expect(ref.encryption_at_rest_provider).to eq("${mongodbatlas_cluster.test.encryption_at_rest_provider}")
        expect(ref.mongo_db_major_version).to eq("${mongodbatlas_cluster.test.mongo_db_major_version}")
        expect(ref.mongo_db_version).to eq("${mongodbatlas_cluster.test.mongo_db_version}")
        expect(ref.mongo_uri).to eq("${mongodbatlas_cluster.test.mongo_uri}")
        expect(ref.mongo_uri_updated).to eq("${mongodbatlas_cluster.test.mongo_uri_updated}")
        expect(ref.mongo_uri_with_options).to eq("${mongodbatlas_cluster.test.mongo_uri_with_options}")
        expect(ref.num_shards).to eq("${mongodbatlas_cluster.test.num_shards}")
        expect(ref.paused).to eq("${mongodbatlas_cluster.test.paused}")
        expect(ref.pit_enabled).to eq("${mongodbatlas_cluster.test.pit_enabled}")
        expect(ref.provider_auto_scaling_compute_max_instance_size).to eq("${mongodbatlas_cluster.test.provider_auto_scaling_compute_max_instance_size}")
        expect(ref.provider_auto_scaling_compute_min_instance_size).to eq("${mongodbatlas_cluster.test.provider_auto_scaling_compute_min_instance_size}")
        expect(ref.provider_disk_iops).to eq("${mongodbatlas_cluster.test.provider_disk_iops}")
        expect(ref.provider_disk_type_name).to eq("${mongodbatlas_cluster.test.provider_disk_type_name}")
        expect(ref.provider_encrypt_ebs_volume).to eq("${mongodbatlas_cluster.test.provider_encrypt_ebs_volume}")
        expect(ref.provider_encrypt_ebs_volume_flag).to eq("${mongodbatlas_cluster.test.provider_encrypt_ebs_volume_flag}")
        expect(ref.provider_region_name).to eq("${mongodbatlas_cluster.test.provider_region_name}")
        expect(ref.provider_volume_type).to eq("${mongodbatlas_cluster.test.provider_volume_type}")
        expect(ref.redact_client_log_data).to eq("${mongodbatlas_cluster.test.redact_client_log_data}")
        expect(ref.replication_factor).to eq("${mongodbatlas_cluster.test.replication_factor}")
        expect(ref.snapshot_backup_policy).to eq("${mongodbatlas_cluster.test.snapshot_backup_policy}")
        expect(ref.srv_address).to eq("${mongodbatlas_cluster.test.srv_address}")
        expect(ref.state_name).to eq("${mongodbatlas_cluster.test.state_name}")
        expect(ref.termination_protection_enabled).to eq("${mongodbatlas_cluster.test.termination_protection_enabled}")
        expect(ref.version_release_system).to eq("${mongodbatlas_cluster.test.version_release_system}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'test')
        expect(config).not_to have_key('accept_data_risks_and_force_replica_set_reconfig')
        expect(config).not_to have_key('auto_scaling_compute_enabled')
        expect(config).not_to have_key('auto_scaling_compute_scale_down_enabled')
        expect(config).not_to have_key('auto_scaling_disk_gb_enabled')
        expect(config).not_to have_key('backing_provider_name')
        expect(config).not_to have_key('backup_enabled')
        expect(config).not_to have_key('cloud_backup')
        expect(config).not_to have_key('cluster_id')
        expect(config).not_to have_key('cluster_type')
        expect(config).not_to have_key('connection_strings')
        expect(config).not_to have_key('container_id')
        expect(config).not_to have_key('disk_size_gb')
        expect(config).not_to have_key('encryption_at_rest_provider')
        expect(config).not_to have_key('mongo_db_major_version')
        expect(config).not_to have_key('mongo_db_version')
        expect(config).not_to have_key('mongo_uri')
        expect(config).not_to have_key('mongo_uri_updated')
        expect(config).not_to have_key('mongo_uri_with_options')
        expect(config).not_to have_key('num_shards')
        expect(config).not_to have_key('paused')
        expect(config).not_to have_key('pit_enabled')
        expect(config).not_to have_key('provider_auto_scaling_compute_max_instance_size')
        expect(config).not_to have_key('provider_auto_scaling_compute_min_instance_size')
        expect(config).not_to have_key('provider_disk_iops')
        expect(config).not_to have_key('provider_disk_type_name')
        expect(config).not_to have_key('provider_encrypt_ebs_volume')
        expect(config).not_to have_key('provider_encrypt_ebs_volume_flag')
        expect(config).not_to have_key('provider_region_name')
        expect(config).not_to have_key('provider_volume_type')
        expect(config).not_to have_key('redact_client_log_data')
        expect(config).not_to have_key('replication_factor')
        expect(config).not_to have_key('snapshot_backup_policy')
        expect(config).not_to have_key('srv_address')
        expect(config).not_to have_key('state_name')
        expect(config).not_to have_key('termination_protection_enabled')
        expect(config).not_to have_key('version_release_system')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ advanced_configuration: [{ 'key1' => 'val1' }], bi_connector_config: [{ 'key1' => 'val1' }], labels: [{ 'key1' => 'val1' }], pinned_fcv: [{ 'key1' => 'val1' }], replication_specs: [{ 'key1' => 'val1' }], retain_backups_enabled: true, tags: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'full')
        expect(config).to have_key('advanced_configuration')
        expect(config).to have_key('bi_connector_config')
        expect(config).to have_key('labels')
        expect(config).to have_key('pinned_fcv')
        expect(config).to have_key('replication_specs')
        expect(config).to have_key('retain_backups_enabled')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes advanced_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(advanced_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('advanced_configuration')
      end

      it 'omits advanced_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('advanced_configuration')
      end
      it 'includes bi_connector_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(bi_connector_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('bi_connector_config')
      end

      it 'omits bi_connector_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('bi_connector_config')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(labels: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes pinned_fcv when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(pinned_fcv: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('pinned_fcv')
      end

      it 'omits pinned_fcv when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('pinned_fcv')
      end
      it 'includes replication_specs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(replication_specs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('replication_specs')
      end

      it 'omits replication_specs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('replication_specs')
      end
      it 'includes retain_backups_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(retain_backups_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('retain_backups_enabled')
      end

      it 'omits retain_backups_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('retain_backups_enabled')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('opt', required_attrs.merge(tags: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts retain_backups_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(retain_backups_enabled: val)
          synth.mongodbatlas_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'mongodbatlas_cluster', "bool_#{val}")
          expect(config['retain_backups_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_cluster', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_instance_size_name']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_cluster('first', required_attrs)
        synth.mongodbatlas_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_cluster,
    method: :mongodbatlas_cluster,
    required_attrs: { name: 'test-value', project_id: 'test-value', provider_instance_size_name: 'test-value', provider_name: 'test-value' },
    expected_outputs: [:id, :accept_data_risks_and_force_replica_set_reconfig, :auto_scaling_compute_enabled, :auto_scaling_compute_scale_down_enabled, :auto_scaling_disk_gb_enabled, :backing_provider_name, :backup_enabled, :cloud_backup, :cluster_id, :cluster_type, :connection_strings, :container_id, :disk_size_gb, :encryption_at_rest_provider, :mongo_db_major_version, :mongo_db_version, :mongo_uri, :mongo_uri_updated, :mongo_uri_with_options, :num_shards, :paused, :pit_enabled, :provider_auto_scaling_compute_max_instance_size, :provider_auto_scaling_compute_min_instance_size, :provider_disk_iops, :provider_disk_type_name, :provider_encrypt_ebs_volume, :provider_encrypt_ebs_volume_flag, :provider_region_name, :provider_volume_type, :redact_client_log_data, :replication_factor, :snapshot_backup_policy, :srv_address, :state_name, :termination_protection_enabled, :version_release_system],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:retain_backups_enabled]
end
