# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_network_peering resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasNetworkPeering do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { container_id: 'test-value', project_id: 'test-value', provider_name: 'test-value' } }

  describe ':mongodbatlas_network_peering' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_peering('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_network_peering', 'test')
        validate_required_attributes(config, [:container_id, :project_id, :provider_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_network_peering('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_network_peering)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_network_peering('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_network_peering.test.id}")
        expect(ref.accepter_region_name).to eq("${mongodbatlas_network_peering.test.accepter_region_name}")
        expect(ref.atlas_cidr_block).to eq("${mongodbatlas_network_peering.test.atlas_cidr_block}")
        expect(ref.atlas_gcp_project_id).to eq("${mongodbatlas_network_peering.test.atlas_gcp_project_id}")
        expect(ref.atlas_id).to eq("${mongodbatlas_network_peering.test.atlas_id}")
        expect(ref.atlas_vpc_name).to eq("${mongodbatlas_network_peering.test.atlas_vpc_name}")
        expect(ref.aws_account_id).to eq("${mongodbatlas_network_peering.test.aws_account_id}")
        expect(ref.azure_directory_id).to eq("${mongodbatlas_network_peering.test.azure_directory_id}")
        expect(ref.azure_subscription_id).to eq("${mongodbatlas_network_peering.test.azure_subscription_id}")
        expect(ref.connection_id).to eq("${mongodbatlas_network_peering.test.connection_id}")
        expect(ref.error_message).to eq("${mongodbatlas_network_peering.test.error_message}")
        expect(ref.error_state).to eq("${mongodbatlas_network_peering.test.error_state}")
        expect(ref.error_state_name).to eq("${mongodbatlas_network_peering.test.error_state_name}")
        expect(ref.gcp_project_id).to eq("${mongodbatlas_network_peering.test.gcp_project_id}")
        expect(ref.network_name).to eq("${mongodbatlas_network_peering.test.network_name}")
        expect(ref.peer_id).to eq("${mongodbatlas_network_peering.test.peer_id}")
        expect(ref.resource_group_name).to eq("${mongodbatlas_network_peering.test.resource_group_name}")
        expect(ref.route_table_cidr_block).to eq("${mongodbatlas_network_peering.test.route_table_cidr_block}")
        expect(ref.status).to eq("${mongodbatlas_network_peering.test.status}")
        expect(ref.status_name).to eq("${mongodbatlas_network_peering.test.status_name}")
        expect(ref.vnet_name).to eq("${mongodbatlas_network_peering.test.vnet_name}")
        expect(ref.vpc_id).to eq("${mongodbatlas_network_peering.test.vpc_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_peering('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_network_peering', 'test')
        expect(config).not_to have_key('accepter_region_name')
        expect(config).not_to have_key('atlas_cidr_block')
        expect(config).not_to have_key('atlas_gcp_project_id')
        expect(config).not_to have_key('atlas_id')
        expect(config).not_to have_key('atlas_vpc_name')
        expect(config).not_to have_key('aws_account_id')
        expect(config).not_to have_key('azure_directory_id')
        expect(config).not_to have_key('azure_subscription_id')
        expect(config).not_to have_key('connection_id')
        expect(config).not_to have_key('error_message')
        expect(config).not_to have_key('error_state')
        expect(config).not_to have_key('error_state_name')
        expect(config).not_to have_key('gcp_project_id')
        expect(config).not_to have_key('network_name')
        expect(config).not_to have_key('peer_id')
        expect(config).not_to have_key('resource_group_name')
        expect(config).not_to have_key('route_table_cidr_block')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('status_name')
        expect(config).not_to have_key('vnet_name')
        expect(config).not_to have_key('vpc_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_peering('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_network_peering', 'typed')
        expect(config['container_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['provider_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_network_peering('first', required_attrs)
        synth.mongodbatlas_network_peering('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_network_peering')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_network_peering,
    method: :mongodbatlas_network_peering,
    required_attrs: { container_id: 'test-value', project_id: 'test-value', provider_name: 'test-value' },
    expected_outputs: [:id, :accepter_region_name, :atlas_cidr_block, :atlas_gcp_project_id, :atlas_id, :atlas_vpc_name, :aws_account_id, :azure_directory_id, :azure_subscription_id, :connection_id, :error_message, :error_state, :error_state_name, :gcp_project_id, :network_name, :peer_id, :resource_group_name, :route_table_cidr_block, :status, :status_name, :vnet_name, :vpc_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
