# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_push_based_log_export resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasPushBasedLogExport do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { bucket_name: 'test-value', iam_role_id: 'test-value', project_id: 'test-value' } }

  describe ':mongodbatlas_push_based_log_export' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_push_based_log_export', 'test')
        validate_required_attributes(config, [:bucket_name, :iam_role_id, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_push_based_log_export('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_push_based_log_export)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_push_based_log_export('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_push_based_log_export.test.id}")
        expect(ref.create_date).to eq("${mongodbatlas_push_based_log_export.test.create_date}")
        expect(ref.prefix_path).to eq("${mongodbatlas_push_based_log_export.test.prefix_path}")
        expect(ref.state).to eq("${mongodbatlas_push_based_log_export.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_push_based_log_export', 'test')
        expect(config).not_to have_key('create_date')
        expect(config).not_to have_key('prefix_path')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ timeouts: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_push_based_log_export', 'full')
        expect(config).to have_key('timeouts')
      end
    end

    context 'optional attributes' do
      it 'includes timeouts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('opt', required_attrs.merge(timeouts: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_push_based_log_export', 'opt')
        expect(config).to have_key('timeouts')
      end

      it 'omits timeouts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_push_based_log_export', 'minimal')
        expect(config).not_to have_key('timeouts')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_push_based_log_export', 'typed')
        expect(config['bucket_name']).to be_a(String)
        expect(config['iam_role_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_push_based_log_export('first', required_attrs)
        synth.mongodbatlas_push_based_log_export('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_push_based_log_export')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_push_based_log_export,
    method: :mongodbatlas_push_based_log_export,
    required_attrs: { bucket_name: 'test-value', iam_role_id: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :create_date, :prefix_path, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
