# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_federated_settings_org_role_mapping resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasFederatedSettingsOrgRoleMapping do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { external_group_name: 'test-value', federation_settings_id: 'test-value', org_id: 'test-value', role_assignments: [{ 'key1' => 'val1' }] } }

  describe ':mongodbatlas_federated_settings_org_role_mapping' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_role_mapping('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_role_mapping', 'test')
        validate_required_attributes(config, [:external_group_name, :federation_settings_id, :org_id, :role_assignments])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_settings_org_role_mapping('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_federated_settings_org_role_mapping)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_federated_settings_org_role_mapping('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_federated_settings_org_role_mapping.test.id}")
        expect(ref.role_mapping_id).to eq("${mongodbatlas_federated_settings_org_role_mapping.test.role_mapping_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_role_mapping('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_role_mapping', 'test')
        expect(config).not_to have_key('role_mapping_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_role_mapping('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_federated_settings_org_role_mapping', 'typed')
        expect(config['external_group_name']).to be_a(String)
        expect(config['federation_settings_id']).to be_a(String)
        expect(config['org_id']).to be_a(String)
        expect(config['role_assignments']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_federated_settings_org_role_mapping('first', required_attrs)
        synth.mongodbatlas_federated_settings_org_role_mapping('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_federated_settings_org_role_mapping')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_federated_settings_org_role_mapping,
    method: :mongodbatlas_federated_settings_org_role_mapping,
    required_attrs: { external_group_name: 'test-value', federation_settings_id: 'test-value', org_id: 'test-value', role_assignments: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :role_mapping_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
