# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_database_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasDatabaseUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { auth_database_name: 'test-value', project_id: 'test-value', username: 'test-value' } }

  describe ':mongodbatlas_database_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'test')
        validate_required_attributes(config, [:auth_database_name, :project_id, :username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_database_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_database_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_database_user('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_database_user.test.id}")
        expect(ref.aws_iam_type).to eq("${mongodbatlas_database_user.test.aws_iam_type}")
        expect(ref.ldap_auth_type).to eq("${mongodbatlas_database_user.test.ldap_auth_type}")
        expect(ref.oidc_auth_type).to eq("${mongodbatlas_database_user.test.oidc_auth_type}")
        expect(ref.x509_type).to eq("${mongodbatlas_database_user.test.x509_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'test')
        expect(config).not_to have_key('aws_iam_type')
        expect(config).not_to have_key('ldap_auth_type')
        expect(config).not_to have_key('oidc_auth_type')
        expect(config).not_to have_key('x509_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', labels: [{ 'key1' => 'val1' }], password: 'test-value', roles: [{ 'key1' => 'val1' }], scopes: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('labels')
        expect(config).to have_key('password')
        expect(config).to have_key('roles')
        expect(config).to have_key('scopes')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('opt', required_attrs.merge(labels: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('opt', required_attrs.merge(password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'opt')
        expect(config).to have_key('password')
      end

      it 'omits password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'minimal')
        expect(config).not_to have_key('password')
      end
      it 'includes roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('opt', required_attrs.merge(roles: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'opt')
        expect(config).to have_key('roles')
      end

      it 'omits roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'minimal')
        expect(config).not_to have_key('roles')
      end
      it 'includes scopes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('opt', required_attrs.merge(scopes: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'opt')
        expect(config).to have_key('scopes')
      end

      it 'omits scopes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'minimal')
        expect(config).not_to have_key('scopes')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_database_user', 'typed')
        expect(config['auth_database_name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_database_user('first', required_attrs)
        synth.mongodbatlas_database_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_database_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_database_user,
    method: :mongodbatlas_database_user,
    required_attrs: { auth_database_name: 'test-value', project_id: 'test-value', username: 'test-value' },
    expected_outputs: [:id, :aws_iam_type, :ldap_auth_type, :oidc_auth_type, :x509_type],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: []
end
