# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_api_key_project_assignment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasApiKeyProjectAssignment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_key_id: 'test-value', project_id: 'test-value', roles: ['test-value'] } }

  describe ':mongodbatlas_api_key_project_assignment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_api_key_project_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_api_key_project_assignment', 'test')
        validate_required_attributes(config, [:api_key_id, :project_id, :roles])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_api_key_project_assignment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_api_key_project_assignment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_api_key_project_assignment('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_api_key_project_assignment.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_api_key_project_assignment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_api_key_project_assignment', 'typed')
        expect(config['api_key_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['roles']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_api_key_project_assignment('first', required_attrs)
        synth.mongodbatlas_api_key_project_assignment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_api_key_project_assignment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_api_key_project_assignment,
    method: :mongodbatlas_api_key_project_assignment,
    required_attrs: { api_key_id: 'test-value', project_id: 'test-value', roles: ['test-value'] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
