# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_event_trigger resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasEventTrigger do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app_id: 'test-value', name: 'test-value', project_id: 'test-value', type: 'test-value' } }

  describe ':mongodbatlas_event_trigger' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'test')
        validate_required_attributes(config, [:app_id, :name, :project_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_event_trigger('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_event_trigger)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_event_trigger('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_event_trigger.test.id}")
        expect(ref.config_collection).to eq("${mongodbatlas_event_trigger.test.config_collection}")
        expect(ref.config_database).to eq("${mongodbatlas_event_trigger.test.config_database}")
        expect(ref.config_full_document).to eq("${mongodbatlas_event_trigger.test.config_full_document}")
        expect(ref.config_full_document_before).to eq("${mongodbatlas_event_trigger.test.config_full_document_before}")
        expect(ref.config_match).to eq("${mongodbatlas_event_trigger.test.config_match}")
        expect(ref.config_operation_type).to eq("${mongodbatlas_event_trigger.test.config_operation_type}")
        expect(ref.config_operation_types).to eq("${mongodbatlas_event_trigger.test.config_operation_types}")
        expect(ref.config_project).to eq("${mongodbatlas_event_trigger.test.config_project}")
        expect(ref.config_providers).to eq("${mongodbatlas_event_trigger.test.config_providers}")
        expect(ref.config_schedule).to eq("${mongodbatlas_event_trigger.test.config_schedule}")
        expect(ref.config_schedule_type).to eq("${mongodbatlas_event_trigger.test.config_schedule_type}")
        expect(ref.config_service_id).to eq("${mongodbatlas_event_trigger.test.config_service_id}")
        expect(ref.disabled).to eq("${mongodbatlas_event_trigger.test.disabled}")
        expect(ref.function_name).to eq("${mongodbatlas_event_trigger.test.function_name}")
        expect(ref.trigger_id).to eq("${mongodbatlas_event_trigger.test.trigger_id}")
        expect(ref.unordered).to eq("${mongodbatlas_event_trigger.test.unordered}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'test')
        expect(config).not_to have_key('config_collection')
        expect(config).not_to have_key('config_database')
        expect(config).not_to have_key('config_full_document')
        expect(config).not_to have_key('config_full_document_before')
        expect(config).not_to have_key('config_match')
        expect(config).not_to have_key('config_operation_type')
        expect(config).not_to have_key('config_operation_types')
        expect(config).not_to have_key('config_project')
        expect(config).not_to have_key('config_providers')
        expect(config).not_to have_key('config_schedule')
        expect(config).not_to have_key('config_schedule_type')
        expect(config).not_to have_key('config_service_id')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('function_name')
        expect(config).not_to have_key('trigger_id')
        expect(config).not_to have_key('unordered')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ event_processors: [{ 'key1' => 'val1' }], function_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'full')
        expect(config).to have_key('event_processors')
        expect(config).to have_key('function_id')
      end
    end

    context 'optional attributes' do
      it 'includes event_processors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('opt', required_attrs.merge(event_processors: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'opt')
        expect(config).to have_key('event_processors')
      end

      it 'omits event_processors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'minimal')
        expect(config).not_to have_key('event_processors')
      end
      it 'includes function_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('opt', required_attrs.merge(function_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'opt')
        expect(config).to have_key('function_id')
      end

      it 'omits function_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'minimal')
        expect(config).not_to have_key('function_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_event_trigger', 'typed')
        expect(config['app_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_event_trigger('first', required_attrs)
        synth.mongodbatlas_event_trigger('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_event_trigger')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_event_trigger,
    method: :mongodbatlas_event_trigger,
    required_attrs: { app_id: 'test-value', name: 'test-value', project_id: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :config_collection, :config_database, :config_full_document, :config_full_document_before, :config_match, :config_operation_type, :config_operation_types, :config_project, :config_providers, :config_schedule, :config_schedule_type, :config_service_id, :disabled, :function_name, :trigger_id, :unordered],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
