# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a mongodbatlas_resource_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::MongodbatlasResourcePolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', org_id: 'test-value', policies: [{ 'key1' => 'val1' }] } }

  describe ':mongodbatlas_resource_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'mongodbatlas_resource_policy', 'test')
        validate_required_attributes(config, [:name, :org_id, :policies])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_resource_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:mongodbatlas_resource_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.mongodbatlas_resource_policy('test', required_attrs)

        expect(ref.id).to eq("${mongodbatlas_resource_policy.test.id}")
        expect(ref.created_by_user).to eq("${mongodbatlas_resource_policy.test.created_by_user}")
        expect(ref.created_date).to eq("${mongodbatlas_resource_policy.test.created_date}")
        expect(ref.last_updated_by_user).to eq("${mongodbatlas_resource_policy.test.last_updated_by_user}")
        expect(ref.last_updated_date).to eq("${mongodbatlas_resource_policy.test.last_updated_date}")
        expect(ref.version).to eq("${mongodbatlas_resource_policy.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_resource_policy', 'test')
        expect(config).not_to have_key('created_by_user')
        expect(config).not_to have_key('created_date')
        expect(config).not_to have_key('last_updated_by_user')
        expect(config).not_to have_key('last_updated_date')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_resource_policy', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_resource_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'mongodbatlas_resource_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'mongodbatlas_resource_policy', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['org_id']).to be_a(String)
        expect(config['policies']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.mongodbatlas_resource_policy('first', required_attrs)
        synth.mongodbatlas_resource_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'mongodbatlas_resource_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :mongodbatlas_resource_policy,
    method: :mongodbatlas_resource_policy,
    required_attrs: { name: 'test-value', org_id: 'test-value', policies: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :created_by_user, :created_date, :last_updated_by_user, :last_updated_date, :version],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
